// split UIKit bindings generated by tool/gen_objc_packages.dart for objc_uikit/uikit_gestures.
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objc_uikit/src/uikit_core_bindings.dart' as imp$1;
import 'package:objc_uikit/src/uikit_gesture_base_bindings.dart' as imp$2;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

extension type UILongPressGestureRecognizer._(objc.ObjCObject object$)
    implements objc.ObjCObject, imp$2.UIGestureRecognizer {
  /// Constructs a [UILongPressGestureRecognizer] that points to the same underlying object as [other].
  UILongPressGestureRecognizer.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [UILongPressGestureRecognizer] that wraps the given raw object pointer.
  UILongPressGestureRecognizer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [UILongPressGestureRecognizer].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_UILongPressGestureRecognizer,
        );

  static UILongPressGestureRecognizer alloc() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UILongPressGestureRecognizer,
      _sel_alloc,
    );
    return UILongPressGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UILongPressGestureRecognizer allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_t1idez(
      _class_UILongPressGestureRecognizer,
      _sel_allocWithZone_,
      zone,
    );
    return UILongPressGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UILongPressGestureRecognizer new$() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UILongPressGestureRecognizer,
      _sel_new,
    );
    return UILongPressGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of UILongPressGestureRecognizer constructed with the default `new` method.
  UILongPressGestureRecognizer() : this.as(new$());
}

extension UILongPressGestureRecognizer$Methods on UILongPressGestureRecognizer {
  double get allowableMovement {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer.allowableMovement',
      iOS: (false, (3, 2, 0)),
    );
    return objc.useMsgSendVariants
        ? _objc_msgSend_6hbhvbFpret(object$.ref.pointer, _sel_allowableMovement)
        : _objc_msgSend_6hbhvb(object$.ref.pointer, _sel_allowableMovement);
  }

  UILongPressGestureRecognizer init() {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_b5i7vq(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return UILongPressGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UILongPressGestureRecognizer initWithCoder(objc.NSCoder coder) {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer.initWithCoder:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_s18bu6(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithCoder_,
      coder.ref.pointer,
    );
    return UILongPressGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UILongPressGestureRecognizer initWithTarget(
    objc.ObjCObject? target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer.initWithTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_zimmlm(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithTarget_action_,
      target?.ref.pointer ?? ffi.nullptr,
      action,
    );
    return UILongPressGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  double get minimumPressDuration {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer.minimumPressDuration',
      iOS: (false, (3, 2, 0)),
    );
    return objc.useMsgSendVariants
        ? _objc_msgSend_6hbhvbFpret(
            object$.ref.pointer,
            _sel_minimumPressDuration,
          )
        : _objc_msgSend_6hbhvb(object$.ref.pointer, _sel_minimumPressDuration);
  }

  int get numberOfTapsRequired {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer.numberOfTapsRequired',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_84sea1(object$.ref.pointer, _sel_numberOfTapsRequired);
  }

  int get numberOfTouchesRequired {
    return _objc_msgSend_84sea1(
      object$.ref.pointer,
      _sel_numberOfTouchesRequired,
    );
  }

  set allowableMovement(double value) {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer.setAllowableMovement:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_1d5a97t(
      object$.ref.pointer,
      _sel_setAllowableMovement_,
      value,
    );
  }

  set minimumPressDuration(double value) {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer.setMinimumPressDuration:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_1d5a97t(
      object$.ref.pointer,
      _sel_setMinimumPressDuration_,
      value,
    );
  }

  set numberOfTapsRequired(int value) {
    objc.checkOsVersionInternal(
      'UILongPressGestureRecognizer.setNumberOfTapsRequired:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_hmwpbn(
      object$.ref.pointer,
      _sel_setNumberOfTapsRequired_,
      value,
    );
  }

  set numberOfTouchesRequired(int value) {
    _objc_msgSend_hmwpbn(
      object$.ref.pointer,
      _sel_setNumberOfTouchesRequired_,
      value,
    );
  }
}

extension type UIPanGestureRecognizer._(objc.ObjCObject object$)
    implements objc.ObjCObject, imp$2.UIGestureRecognizer {
  /// Constructs a [UIPanGestureRecognizer] that points to the same underlying object as [other].
  UIPanGestureRecognizer.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [UIPanGestureRecognizer] that wraps the given raw object pointer.
  UIPanGestureRecognizer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [UIPanGestureRecognizer].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_UIPanGestureRecognizer,
        );

  static UIPanGestureRecognizer alloc() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UIPanGestureRecognizer,
      _sel_alloc,
    );
    return UIPanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UIPanGestureRecognizer allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_t1idez(
      _class_UIPanGestureRecognizer,
      _sel_allocWithZone_,
      zone,
    );
    return UIPanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UIPanGestureRecognizer new$() {
    final $ret = _objc_msgSend_b5i7vq(_class_UIPanGestureRecognizer, _sel_new);
    return UIPanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of UIPanGestureRecognizer constructed with the default `new` method.
  UIPanGestureRecognizer() : this.as(new$());
}

extension UIPanGestureRecognizer$Methods on UIPanGestureRecognizer {
  int get allowedScrollTypesMask {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer.allowedScrollTypesMask',
      iOS: (false, (13, 4, 0)),
    );
    return _objc_msgSend_1q9qz9z(
      object$.ref.pointer,
      _sel_allowedScrollTypesMask,
    );
  }

  UIPanGestureRecognizer init() {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_b5i7vq(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return UIPanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UIPanGestureRecognizer initWithCoder(objc.NSCoder coder) {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer.initWithCoder:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_s18bu6(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithCoder_,
      coder.ref.pointer,
    );
    return UIPanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UIPanGestureRecognizer initWithTarget(
    objc.ObjCObject? target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer.initWithTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_zimmlm(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithTarget_action_,
      target?.ref.pointer ?? ffi.nullptr,
      action,
    );
    return UIPanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  int get maximumNumberOfTouches {
    return _objc_msgSend_84sea1(
      object$.ref.pointer,
      _sel_maximumNumberOfTouches,
    );
  }

  int get minimumNumberOfTouches {
    return _objc_msgSend_84sea1(
      object$.ref.pointer,
      _sel_minimumNumberOfTouches,
    );
  }

  set allowedScrollTypesMask(int value) {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer.setAllowedScrollTypesMask:',
      iOS: (false, (13, 4, 0)),
    );
    _objc_msgSend_1uc0y0h(
      object$.ref.pointer,
      _sel_setAllowedScrollTypesMask_,
      value,
    );
  }

  set maximumNumberOfTouches(int value) {
    _objc_msgSend_hmwpbn(
      object$.ref.pointer,
      _sel_setMaximumNumberOfTouches_,
      value,
    );
  }

  set minimumNumberOfTouches(int value) {
    _objc_msgSend_hmwpbn(
      object$.ref.pointer,
      _sel_setMinimumNumberOfTouches_,
      value,
    );
  }

  void setTranslation(objc.CGPoint translation, {imp$1.UIView? inView}) {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer.setTranslation:inView:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_1pgdfdc(
      object$.ref.pointer,
      _sel_setTranslation_inView_,
      translation,
      inView?.ref.pointer ?? ffi.nullptr,
    );
  }

  objc.CGPoint translationInView(imp$1.UIView? view) {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer.translationInView:',
      iOS: (false, (3, 2, 0)),
    );
    final $ptr = pkg_ffi.calloc<objc.CGPoint>();
    objc.useMsgSendVariants
        ? _objc_msgSend_4j9k4pStret(
            $ptr,
            object$.ref.pointer,
            _sel_translationInView_,
            view?.ref.pointer ?? ffi.nullptr,
          )
        : $ptr.ref = _objc_msgSend_4j9k4p(
            object$.ref.pointer,
            _sel_translationInView_,
            view?.ref.pointer ?? ffi.nullptr,
          );
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<objc.CGPoint>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<objc.CGPoint>($finalizable);
  }

  objc.CGPoint velocityInView(imp$1.UIView? view) {
    objc.checkOsVersionInternal(
      'UIPanGestureRecognizer.velocityInView:',
      iOS: (false, (3, 2, 0)),
    );
    final $ptr = pkg_ffi.calloc<objc.CGPoint>();
    objc.useMsgSendVariants
        ? _objc_msgSend_4j9k4pStret(
            $ptr,
            object$.ref.pointer,
            _sel_velocityInView_,
            view?.ref.pointer ?? ffi.nullptr,
          )
        : $ptr.ref = _objc_msgSend_4j9k4p(
            object$.ref.pointer,
            _sel_velocityInView_,
            view?.ref.pointer ?? ffi.nullptr,
          );
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<objc.CGPoint>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<objc.CGPoint>($finalizable);
  }
}

extension type UIPinchGestureRecognizer._(objc.ObjCObject object$)
    implements objc.ObjCObject, imp$2.UIGestureRecognizer {
  /// Constructs a [UIPinchGestureRecognizer] that points to the same underlying object as [other].
  UIPinchGestureRecognizer.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'UIPinchGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [UIPinchGestureRecognizer] that wraps the given raw object pointer.
  UIPinchGestureRecognizer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'UIPinchGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [UIPinchGestureRecognizer].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_UIPinchGestureRecognizer,
        );

  static UIPinchGestureRecognizer alloc() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UIPinchGestureRecognizer,
      _sel_alloc,
    );
    return UIPinchGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UIPinchGestureRecognizer allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_t1idez(
      _class_UIPinchGestureRecognizer,
      _sel_allocWithZone_,
      zone,
    );
    return UIPinchGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UIPinchGestureRecognizer new$() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UIPinchGestureRecognizer,
      _sel_new,
    );
    return UIPinchGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of UIPinchGestureRecognizer constructed with the default `new` method.
  UIPinchGestureRecognizer() : this.as(new$());
}

extension UIPinchGestureRecognizer$Methods on UIPinchGestureRecognizer {
  UIPinchGestureRecognizer init() {
    objc.checkOsVersionInternal(
      'UIPinchGestureRecognizer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_b5i7vq(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return UIPinchGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UIPinchGestureRecognizer initWithCoder(objc.NSCoder coder) {
    objc.checkOsVersionInternal(
      'UIPinchGestureRecognizer.initWithCoder:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_s18bu6(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithCoder_,
      coder.ref.pointer,
    );
    return UIPinchGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UIPinchGestureRecognizer initWithTarget(
    objc.ObjCObject? target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UIPinchGestureRecognizer.initWithTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_zimmlm(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithTarget_action_,
      target?.ref.pointer ?? ffi.nullptr,
      action,
    );
    return UIPinchGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  double get scale {
    objc.checkOsVersionInternal(
      'UIPinchGestureRecognizer.scale',
      iOS: (false, (3, 2, 0)),
    );
    return objc.useMsgSendVariants
        ? _objc_msgSend_6hbhvbFpret(object$.ref.pointer, _sel_scale)
        : _objc_msgSend_6hbhvb(object$.ref.pointer, _sel_scale);
  }

  set scale(double value) {
    objc.checkOsVersionInternal(
      'UIPinchGestureRecognizer.setScale:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_1d5a97t(object$.ref.pointer, _sel_setScale_, value);
  }

  double get velocity {
    objc.checkOsVersionInternal(
      'UIPinchGestureRecognizer.velocity',
      iOS: (false, (3, 2, 0)),
    );
    return objc.useMsgSendVariants
        ? _objc_msgSend_6hbhvbFpret(object$.ref.pointer, _sel_velocity)
        : _objc_msgSend_6hbhvb(object$.ref.pointer, _sel_velocity);
  }
}

extension type UIRotationGestureRecognizer._(objc.ObjCObject object$)
    implements objc.ObjCObject, imp$2.UIGestureRecognizer {
  /// Constructs a [UIRotationGestureRecognizer] that points to the same underlying object as [other].
  UIRotationGestureRecognizer.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'UIRotationGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [UIRotationGestureRecognizer] that wraps the given raw object pointer.
  UIRotationGestureRecognizer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'UIRotationGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [UIRotationGestureRecognizer].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_UIRotationGestureRecognizer,
        );

  static UIRotationGestureRecognizer alloc() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UIRotationGestureRecognizer,
      _sel_alloc,
    );
    return UIRotationGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UIRotationGestureRecognizer allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_t1idez(
      _class_UIRotationGestureRecognizer,
      _sel_allocWithZone_,
      zone,
    );
    return UIRotationGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UIRotationGestureRecognizer new$() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UIRotationGestureRecognizer,
      _sel_new,
    );
    return UIRotationGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of UIRotationGestureRecognizer constructed with the default `new` method.
  UIRotationGestureRecognizer() : this.as(new$());
}

extension UIRotationGestureRecognizer$Methods on UIRotationGestureRecognizer {
  UIRotationGestureRecognizer init() {
    objc.checkOsVersionInternal(
      'UIRotationGestureRecognizer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_b5i7vq(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return UIRotationGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UIRotationGestureRecognizer initWithCoder(objc.NSCoder coder) {
    objc.checkOsVersionInternal(
      'UIRotationGestureRecognizer.initWithCoder:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_s18bu6(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithCoder_,
      coder.ref.pointer,
    );
    return UIRotationGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UIRotationGestureRecognizer initWithTarget(
    objc.ObjCObject? target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UIRotationGestureRecognizer.initWithTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_zimmlm(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithTarget_action_,
      target?.ref.pointer ?? ffi.nullptr,
      action,
    );
    return UIRotationGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  double get rotation {
    objc.checkOsVersionInternal(
      'UIRotationGestureRecognizer.rotation',
      iOS: (false, (3, 2, 0)),
    );
    return objc.useMsgSendVariants
        ? _objc_msgSend_6hbhvbFpret(object$.ref.pointer, _sel_rotation)
        : _objc_msgSend_6hbhvb(object$.ref.pointer, _sel_rotation);
  }

  set rotation(double value) {
    objc.checkOsVersionInternal(
      'UIRotationGestureRecognizer.setRotation:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_1d5a97t(object$.ref.pointer, _sel_setRotation_, value);
  }

  double get velocity {
    objc.checkOsVersionInternal(
      'UIRotationGestureRecognizer.velocity',
      iOS: (false, (3, 2, 0)),
    );
    return objc.useMsgSendVariants
        ? _objc_msgSend_6hbhvbFpret(object$.ref.pointer, _sel_velocity)
        : _objc_msgSend_6hbhvb(object$.ref.pointer, _sel_velocity);
  }
}

extension type UIScreenEdgePanGestureRecognizer._(objc.ObjCObject object$)
    implements objc.ObjCObject, UIPanGestureRecognizer {
  /// Constructs a [UIScreenEdgePanGestureRecognizer] that points to the same underlying object as [other].
  UIScreenEdgePanGestureRecognizer.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'UIScreenEdgePanGestureRecognizer',
      iOS: (false, (7, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [UIScreenEdgePanGestureRecognizer] that wraps the given raw object pointer.
  UIScreenEdgePanGestureRecognizer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'UIScreenEdgePanGestureRecognizer',
      iOS: (false, (7, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [UIScreenEdgePanGestureRecognizer].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_UIScreenEdgePanGestureRecognizer,
        );

  static UIScreenEdgePanGestureRecognizer alloc() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UIScreenEdgePanGestureRecognizer,
      _sel_alloc,
    );
    return UIScreenEdgePanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UIScreenEdgePanGestureRecognizer allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_t1idez(
      _class_UIScreenEdgePanGestureRecognizer,
      _sel_allocWithZone_,
      zone,
    );
    return UIScreenEdgePanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UIScreenEdgePanGestureRecognizer new$() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UIScreenEdgePanGestureRecognizer,
      _sel_new,
    );
    return UIScreenEdgePanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of UIScreenEdgePanGestureRecognizer constructed with the default `new` method.
  UIScreenEdgePanGestureRecognizer() : this.as(new$());
}

extension UIScreenEdgePanGestureRecognizer$Methods
    on UIScreenEdgePanGestureRecognizer {
  int get edges {
    objc.checkOsVersionInternal(
      'UIScreenEdgePanGestureRecognizer.edges',
      iOS: (false, (7, 0, 0)),
    );
    return _objc_msgSend_84sea1(object$.ref.pointer, _sel_edges);
  }

  UIScreenEdgePanGestureRecognizer init() {
    objc.checkOsVersionInternal(
      'UIScreenEdgePanGestureRecognizer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_b5i7vq(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return UIScreenEdgePanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UIScreenEdgePanGestureRecognizer initWithCoder(objc.NSCoder coder) {
    objc.checkOsVersionInternal(
      'UIScreenEdgePanGestureRecognizer.initWithCoder:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_s18bu6(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithCoder_,
      coder.ref.pointer,
    );
    return UIScreenEdgePanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UIScreenEdgePanGestureRecognizer initWithTarget(
    objc.ObjCObject? target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UIScreenEdgePanGestureRecognizer.initWithTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_zimmlm(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithTarget_action_,
      target?.ref.pointer ?? ffi.nullptr,
      action,
    );
    return UIScreenEdgePanGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  set edges(int value) {
    objc.checkOsVersionInternal(
      'UIScreenEdgePanGestureRecognizer.setEdges:',
      iOS: (false, (7, 0, 0)),
    );
    _objc_msgSend_hmwpbn(object$.ref.pointer, _sel_setEdges_, value);
  }
}

extension type UISwipeGestureRecognizer._(objc.ObjCObject object$)
    implements objc.ObjCObject, imp$2.UIGestureRecognizer {
  /// Constructs a [UISwipeGestureRecognizer] that points to the same underlying object as [other].
  UISwipeGestureRecognizer.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'UISwipeGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [UISwipeGestureRecognizer] that wraps the given raw object pointer.
  UISwipeGestureRecognizer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'UISwipeGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [UISwipeGestureRecognizer].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_UISwipeGestureRecognizer,
        );

  static UISwipeGestureRecognizer alloc() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UISwipeGestureRecognizer,
      _sel_alloc,
    );
    return UISwipeGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UISwipeGestureRecognizer allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_t1idez(
      _class_UISwipeGestureRecognizer,
      _sel_allocWithZone_,
      zone,
    );
    return UISwipeGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UISwipeGestureRecognizer new$() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UISwipeGestureRecognizer,
      _sel_new,
    );
    return UISwipeGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of UISwipeGestureRecognizer constructed with the default `new` method.
  UISwipeGestureRecognizer() : this.as(new$());
}

extension UISwipeGestureRecognizer$Methods on UISwipeGestureRecognizer {
  int get direction {
    objc.checkOsVersionInternal(
      'UISwipeGestureRecognizer.direction',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_1c9trfg(object$.ref.pointer, _sel_direction);
  }

  UISwipeGestureRecognizer init() {
    objc.checkOsVersionInternal(
      'UISwipeGestureRecognizer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_b5i7vq(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return UISwipeGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UISwipeGestureRecognizer initWithCoder(objc.NSCoder coder) {
    objc.checkOsVersionInternal(
      'UISwipeGestureRecognizer.initWithCoder:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_s18bu6(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithCoder_,
      coder.ref.pointer,
    );
    return UISwipeGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UISwipeGestureRecognizer initWithTarget(
    objc.ObjCObject? target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UISwipeGestureRecognizer.initWithTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_zimmlm(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithTarget_action_,
      target?.ref.pointer ?? ffi.nullptr,
      action,
    );
    return UISwipeGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  int get numberOfTouchesRequired {
    return _objc_msgSend_84sea1(
      object$.ref.pointer,
      _sel_numberOfTouchesRequired,
    );
  }

  set direction(int value) {
    objc.checkOsVersionInternal(
      'UISwipeGestureRecognizer.setDirection:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_1wz0z14(object$.ref.pointer, _sel_setDirection_, value);
  }

  set numberOfTouchesRequired(int value) {
    _objc_msgSend_hmwpbn(
      object$.ref.pointer,
      _sel_setNumberOfTouchesRequired_,
      value,
    );
  }
}

sealed class UISwipeGestureRecognizerDirection {
  static const UISwipeGestureRecognizerDirectionRight = 1;
  static const UISwipeGestureRecognizerDirectionLeft = 2;
  static const UISwipeGestureRecognizerDirectionUp = 4;
  static const UISwipeGestureRecognizerDirectionDown = 8;
}

extension type UITapGestureRecognizer._(objc.ObjCObject object$)
    implements objc.ObjCObject, imp$2.UIGestureRecognizer {
  /// Constructs a [UITapGestureRecognizer] that points to the same underlying object as [other].
  UITapGestureRecognizer.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'UITapGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [UITapGestureRecognizer] that wraps the given raw object pointer.
  UITapGestureRecognizer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'UITapGestureRecognizer',
      iOS: (false, (3, 2, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [UITapGestureRecognizer].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_UITapGestureRecognizer,
        );

  static UITapGestureRecognizer alloc() {
    final $ret = _objc_msgSend_b5i7vq(
      _class_UITapGestureRecognizer,
      _sel_alloc,
    );
    return UITapGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UITapGestureRecognizer allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_t1idez(
      _class_UITapGestureRecognizer,
      _sel_allocWithZone_,
      zone,
    );
    return UITapGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static UITapGestureRecognizer new$() {
    final $ret = _objc_msgSend_b5i7vq(_class_UITapGestureRecognizer, _sel_new);
    return UITapGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of UITapGestureRecognizer constructed with the default `new` method.
  UITapGestureRecognizer() : this.as(new$());
}

extension UITapGestureRecognizer$Methods on UITapGestureRecognizer {
  int get buttonMaskRequired {
    objc.checkOsVersionInternal(
      'UITapGestureRecognizer.buttonMaskRequired',
      iOS: (false, (13, 4, 0)),
    );
    return _objc_msgSend_1q9qz9z(object$.ref.pointer, _sel_buttonMaskRequired);
  }

  UITapGestureRecognizer init() {
    objc.checkOsVersionInternal(
      'UITapGestureRecognizer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_b5i7vq(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return UITapGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UITapGestureRecognizer initWithCoder(objc.NSCoder coder) {
    objc.checkOsVersionInternal(
      'UITapGestureRecognizer.initWithCoder:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_s18bu6(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithCoder_,
      coder.ref.pointer,
    );
    return UITapGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  UITapGestureRecognizer initWithTarget(
    objc.ObjCObject? target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UITapGestureRecognizer.initWithTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_zimmlm(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithTarget_action_,
      target?.ref.pointer ?? ffi.nullptr,
      action,
    );
    return UITapGestureRecognizer.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  int get numberOfTapsRequired {
    objc.checkOsVersionInternal(
      'UITapGestureRecognizer.numberOfTapsRequired',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_84sea1(object$.ref.pointer, _sel_numberOfTapsRequired);
  }

  int get numberOfTouchesRequired {
    return _objc_msgSend_84sea1(
      object$.ref.pointer,
      _sel_numberOfTouchesRequired,
    );
  }

  set buttonMaskRequired(int value) {
    objc.checkOsVersionInternal(
      'UITapGestureRecognizer.setButtonMaskRequired:',
      iOS: (false, (13, 4, 0)),
    );
    _objc_msgSend_1uc0y0h(
      object$.ref.pointer,
      _sel_setButtonMaskRequired_,
      value,
    );
  }

  set numberOfTapsRequired(int value) {
    objc.checkOsVersionInternal(
      'UITapGestureRecognizer.setNumberOfTapsRequired:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_hmwpbn(
      object$.ref.pointer,
      _sel_setNumberOfTapsRequired_,
      value,
    );
  }

  set numberOfTouchesRequired(int value) {
    _objc_msgSend_hmwpbn(
      object$.ref.pointer,
      _sel_setNumberOfTouchesRequired_,
      value,
    );
  }
}

late final _class_UILongPressGestureRecognizer = objc.getClass(
  "UILongPressGestureRecognizer",
);
late final _class_UIPanGestureRecognizer = objc.getClass(
  "UIPanGestureRecognizer",
);
late final _class_UIPinchGestureRecognizer = objc.getClass(
  "UIPinchGestureRecognizer",
);
late final _class_UIRotationGestureRecognizer = objc.getClass(
  "UIRotationGestureRecognizer",
);
late final _class_UIScreenEdgePanGestureRecognizer = objc.getClass(
  "UIScreenEdgePanGestureRecognizer",
);
late final _class_UISwipeGestureRecognizer = objc.getClass(
  "UISwipeGestureRecognizer",
);
late final _class_UITapGestureRecognizer = objc.getClass(
  "UITapGestureRecognizer",
);
final _objc_msgSend_1c9trfg = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.UnsignedLong Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1d5a97t = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Double,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        double,
      )
    >();
final _objc_msgSend_1pgdfdc = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          objc.CGPoint,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        objc.CGPoint,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1q9qz9z = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Long Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1uc0y0h = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_1wz0z14 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.UnsignedLong,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_4j9k4p = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        objc.CGPoint Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      objc.CGPoint Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_4j9k4pStret = objc.msgSendStretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.CGPoint>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.CGPoint>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_6hbhvb = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Double Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_6hbhvbFpret = objc.msgSendFpretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Double Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      double Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_84sea1 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.UnsignedLong Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_b5i7vq = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        imp$1.instancetype Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      imp$1.instancetype Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_hmwpbn = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.UnsignedLong,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_s18bu6 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        imp$1.instancetype Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      imp$1.instancetype Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_t1idez = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        imp$1.instancetype Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      imp$1.instancetype Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
final _objc_msgSend_xat5dx = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_zimmlm = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        imp$1.instancetype Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      imp$1.instancetype Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_alloc = objc.registerName("alloc");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
late final _sel_allowableMovement = objc.registerName("allowableMovement");
late final _sel_allowedScrollTypesMask = objc.registerName(
  "allowedScrollTypesMask",
);
late final _sel_buttonMaskRequired = objc.registerName("buttonMaskRequired");
late final _sel_direction = objc.registerName("direction");
late final _sel_edges = objc.registerName("edges");
late final _sel_init = objc.registerName("init");
late final _sel_initWithCoder_ = objc.registerName("initWithCoder:");
late final _sel_initWithTarget_action_ = objc.registerName(
  "initWithTarget:action:",
);
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
late final _sel_maximumNumberOfTouches = objc.registerName(
  "maximumNumberOfTouches",
);
late final _sel_minimumNumberOfTouches = objc.registerName(
  "minimumNumberOfTouches",
);
late final _sel_minimumPressDuration = objc.registerName(
  "minimumPressDuration",
);
late final _sel_new = objc.registerName("new");
late final _sel_numberOfTapsRequired = objc.registerName(
  "numberOfTapsRequired",
);
late final _sel_numberOfTouchesRequired = objc.registerName(
  "numberOfTouchesRequired",
);
late final _sel_rotation = objc.registerName("rotation");
late final _sel_scale = objc.registerName("scale");
late final _sel_setAllowableMovement_ = objc.registerName(
  "setAllowableMovement:",
);
late final _sel_setAllowedScrollTypesMask_ = objc.registerName(
  "setAllowedScrollTypesMask:",
);
late final _sel_setButtonMaskRequired_ = objc.registerName(
  "setButtonMaskRequired:",
);
late final _sel_setDirection_ = objc.registerName("setDirection:");
late final _sel_setEdges_ = objc.registerName("setEdges:");
late final _sel_setMaximumNumberOfTouches_ = objc.registerName(
  "setMaximumNumberOfTouches:",
);
late final _sel_setMinimumNumberOfTouches_ = objc.registerName(
  "setMinimumNumberOfTouches:",
);
late final _sel_setMinimumPressDuration_ = objc.registerName(
  "setMinimumPressDuration:",
);
late final _sel_setNumberOfTapsRequired_ = objc.registerName(
  "setNumberOfTapsRequired:",
);
late final _sel_setNumberOfTouchesRequired_ = objc.registerName(
  "setNumberOfTouchesRequired:",
);
late final _sel_setRotation_ = objc.registerName("setRotation:");
late final _sel_setScale_ = objc.registerName("setScale:");
late final _sel_setTranslation_inView_ = objc.registerName(
  "setTranslation:inView:",
);
late final _sel_translationInView_ = objc.registerName("translationInView:");
late final _sel_velocity = objc.registerName("velocity");
late final _sel_velocityInView_ = objc.registerName("velocityInView:");
