// split UIKit bindings generated by tool/gen_objc_packages.dart for objc_uikit/uikit_gesture_base.
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objc_uikit/src/uikit_core_bindings.dart' as imp$1;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<objc.ObjCObjectImpl>,
  )
>()
external bool _1ogluep_protocolTrampoline_2n06mv(
  ffi.Pointer<objc.ObjCObjectImpl> target,
  ffi.Pointer<ffi.Void> sel,
  ffi.Pointer<objc.ObjCObjectImpl> arg1,
  ffi.Pointer<objc.ObjCObjectImpl> arg2,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<objc.ObjCObjectImpl>,
  )
>()
external bool _1ogluep_protocolTrampoline_3su7tt(
  ffi.Pointer<objc.ObjCObjectImpl> target,
  ffi.Pointer<ffi.Void> sel,
  ffi.Pointer<objc.ObjCObjectImpl> arg1,
);

/// Construction methods for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer)>`.
abstract final class ObjCBlock_bool_ffiVoid_UIGestureRecognizer {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer)
  >
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer)
      >(pointer, retain: retain, release: release);

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer)
  >
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void> arg0,
          ffi.Pointer<objc.ObjCObjectImpl> arg1,
        )
      >
    >
    ptr,
  ) =>
      objc.ObjCBlock<
        ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer)
      >(
        objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
        retain: false,
        release: true,
      );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer)
  >
  fromFunction(
    bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer) fn, {
    bool keepIsolateAlive = true,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer)
      >(
        objc.newClosureBlock(
          _closureCallable,
          (ffi.Pointer<ffi.Void> arg0, ffi.Pointer<objc.ObjCObjectImpl> arg1) =>
              fn(
                arg0,
                UIGestureRecognizer.fromPointer(
                  arg1,
                  retain: true,
                  release: true,
                ),
              ),
          keepIsolateAlive,
        ),
        retain: false,
        release: true,
      );

  /// Native method trampoline for this block signature.
  static ffi.Pointer<ffi.Void> get protocolTrampoline =>
      ffi.Native.addressOf<
            ffi.NativeFunction<
              ffi.Bool Function(
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<objc.ObjCObjectImpl>,
              )
            >
          >(_1ogluep_protocolTrampoline_3su7tt)
          .cast();

  static bool _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
          )
        >
      >()
      .asFunction<
        bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<objc.ObjCObjectImpl>)
      >()(arg0, arg1);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline, false)
          .cast();
  static bool _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
  ) =>
      (objc.getBlockClosure(block)
          as bool Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          ))(arg0, arg1);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline, false)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer)>`.
extension ObjCBlock_bool_ffiVoid_UIGestureRecognizer$CallExtension
    on
        objc.ObjCBlock<
          ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer)
        > {
  bool call(ffi.Pointer<ffi.Void> arg0, UIGestureRecognizer arg1) => ref
      .pointer
      .ref
      .invoke
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<objc.ObjCBlockImpl>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(ref.pointer, arg0, arg1.ref.pointer);
}

/// Construction methods for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIEvent)>`.
abstract final class ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIEvent {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIEvent)
  >
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          imp$1.UIEvent,
        )
      >(pointer, retain: retain, release: release);

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIEvent)
  >
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void> arg0,
          ffi.Pointer<objc.ObjCObjectImpl> arg1,
          ffi.Pointer<objc.ObjCObjectImpl> arg2,
        )
      >
    >
    ptr,
  ) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          imp$1.UIEvent,
        )
      >(
        objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
        retain: false,
        release: true,
      );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIEvent)
  >
  fromFunction(
    bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIEvent)
    fn, {
    bool keepIsolateAlive = true,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          imp$1.UIEvent,
        )
      >(
        objc.newClosureBlock(
          _closureCallable,
          (
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          ) => fn(
            arg0,
            UIGestureRecognizer.fromPointer(arg1, retain: true, release: true),
            imp$1.UIEvent.fromPointer(arg2, retain: true, release: true),
          ),
          keepIsolateAlive,
        ),
        retain: false,
        release: true,
      );

  /// Native method trampoline for this block signature.
  static ffi.Pointer<ffi.Void> get protocolTrampoline =>
      ffi.Native.addressOf<
            ffi.NativeFunction<
              ffi.Bool Function(
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<objc.ObjCObjectImpl>,
              )
            >
          >(_1ogluep_protocolTrampoline_2n06mv)
          .cast();

  static bool _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline, false)
          .cast();
  static bool _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) =>
      (objc.getBlockClosure(block)
          as bool Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          ))(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline, false)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIEvent)>`.
extension ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIEvent$CallExtension
    on
        objc.ObjCBlock<
          ffi.Bool Function(
            ffi.Pointer<ffi.Void>,
            UIGestureRecognizer,
            imp$1.UIEvent,
          )
        > {
  bool call(
    ffi.Pointer<ffi.Void> arg0,
    UIGestureRecognizer arg1,
    imp$1.UIEvent arg2,
  ) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<objc.ObjCBlockImpl>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(ref.pointer, arg0, arg1.ref.pointer, arg2.ref.pointer);
}

/// Construction methods for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, UIGestureRecognizer)>`.
abstract final class ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIGestureRecognizer {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<
    ffi.Bool Function(
      ffi.Pointer<ffi.Void>,
      UIGestureRecognizer,
      UIGestureRecognizer,
    )
  >
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          UIGestureRecognizer,
        )
      >(pointer, retain: retain, release: release);

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<
    ffi.Bool Function(
      ffi.Pointer<ffi.Void>,
      UIGestureRecognizer,
      UIGestureRecognizer,
    )
  >
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void> arg0,
          ffi.Pointer<objc.ObjCObjectImpl> arg1,
          ffi.Pointer<objc.ObjCObjectImpl> arg2,
        )
      >
    >
    ptr,
  ) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          UIGestureRecognizer,
        )
      >(
        objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
        retain: false,
        release: true,
      );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<
    ffi.Bool Function(
      ffi.Pointer<ffi.Void>,
      UIGestureRecognizer,
      UIGestureRecognizer,
    )
  >
  fromFunction(
    bool Function(
      ffi.Pointer<ffi.Void>,
      UIGestureRecognizer,
      UIGestureRecognizer,
    )
    fn, {
    bool keepIsolateAlive = true,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          UIGestureRecognizer,
        )
      >(
        objc.newClosureBlock(
          _closureCallable,
          (
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          ) => fn(
            arg0,
            UIGestureRecognizer.fromPointer(arg1, retain: true, release: true),
            UIGestureRecognizer.fromPointer(arg2, retain: true, release: true),
          ),
          keepIsolateAlive,
        ),
        retain: false,
        release: true,
      );

  /// Native method trampoline for this block signature.
  static ffi.Pointer<ffi.Void> get protocolTrampoline =>
      ffi.Native.addressOf<
            ffi.NativeFunction<
              ffi.Bool Function(
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<objc.ObjCObjectImpl>,
              )
            >
          >(_1ogluep_protocolTrampoline_2n06mv)
          .cast();

  static bool _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline, false)
          .cast();
  static bool _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) =>
      (objc.getBlockClosure(block)
          as bool Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          ))(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline, false)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, UIGestureRecognizer)>`.
extension ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIGestureRecognizer$CallExtension
    on
        objc.ObjCBlock<
          ffi.Bool Function(
            ffi.Pointer<ffi.Void>,
            UIGestureRecognizer,
            UIGestureRecognizer,
          )
        > {
  bool call(
    ffi.Pointer<ffi.Void> arg0,
    UIGestureRecognizer arg1,
    UIGestureRecognizer arg2,
  ) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<objc.ObjCBlockImpl>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(ref.pointer, arg0, arg1.ref.pointer, arg2.ref.pointer);
}

/// Construction methods for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIPress)>`.
abstract final class ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIPress {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIPress)
  >
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          imp$1.UIPress,
        )
      >(pointer, retain: retain, release: release);

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIPress)
  >
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void> arg0,
          ffi.Pointer<objc.ObjCObjectImpl> arg1,
          ffi.Pointer<objc.ObjCObjectImpl> arg2,
        )
      >
    >
    ptr,
  ) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          imp$1.UIPress,
        )
      >(
        objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
        retain: false,
        release: true,
      );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIPress)
  >
  fromFunction(
    bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIPress)
    fn, {
    bool keepIsolateAlive = true,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          imp$1.UIPress,
        )
      >(
        objc.newClosureBlock(
          _closureCallable,
          (
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          ) => fn(
            arg0,
            UIGestureRecognizer.fromPointer(arg1, retain: true, release: true),
            imp$1.UIPress.fromPointer(arg2, retain: true, release: true),
          ),
          keepIsolateAlive,
        ),
        retain: false,
        release: true,
      );

  /// Native method trampoline for this block signature.
  static ffi.Pointer<ffi.Void> get protocolTrampoline =>
      ffi.Native.addressOf<
            ffi.NativeFunction<
              ffi.Bool Function(
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<objc.ObjCObjectImpl>,
              )
            >
          >(_1ogluep_protocolTrampoline_2n06mv)
          .cast();

  static bool _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline, false)
          .cast();
  static bool _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) =>
      (objc.getBlockClosure(block)
          as bool Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          ))(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline, false)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UIPress)>`.
extension ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIPress$CallExtension
    on
        objc.ObjCBlock<
          ffi.Bool Function(
            ffi.Pointer<ffi.Void>,
            UIGestureRecognizer,
            imp$1.UIPress,
          )
        > {
  bool call(
    ffi.Pointer<ffi.Void> arg0,
    UIGestureRecognizer arg1,
    imp$1.UIPress arg2,
  ) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<objc.ObjCBlockImpl>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(ref.pointer, arg0, arg1.ref.pointer, arg2.ref.pointer);
}

/// Construction methods for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UITouch)>`.
abstract final class ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UITouch {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UITouch)
  >
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          imp$1.UITouch,
        )
      >(pointer, retain: retain, release: release);

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UITouch)
  >
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void> arg0,
          ffi.Pointer<objc.ObjCObjectImpl> arg1,
          ffi.Pointer<objc.ObjCObjectImpl> arg2,
        )
      >
    >
    ptr,
  ) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          imp$1.UITouch,
        )
      >(
        objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
        retain: false,
        release: true,
      );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<
    ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UITouch)
  >
  fromFunction(
    bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UITouch)
    fn, {
    bool keepIsolateAlive = true,
  }) =>
      objc.ObjCBlock<
        ffi.Bool Function(
          ffi.Pointer<ffi.Void>,
          UIGestureRecognizer,
          imp$1.UITouch,
        )
      >(
        objc.newClosureBlock(
          _closureCallable,
          (
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          ) => fn(
            arg0,
            UIGestureRecognizer.fromPointer(arg1, retain: true, release: true),
            imp$1.UITouch.fromPointer(arg2, retain: true, release: true),
          ),
          keepIsolateAlive,
        ),
        retain: false,
        release: true,
      );

  /// Native method trampoline for this block signature.
  static ffi.Pointer<ffi.Void> get protocolTrampoline =>
      ffi.Native.addressOf<
            ffi.NativeFunction<
              ffi.Bool Function(
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<ffi.Void>,
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<objc.ObjCObjectImpl>,
              )
            >
          >(_1ogluep_protocolTrampoline_2n06mv)
          .cast();

  static bool _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_fnPtrTrampoline, false)
          .cast();
  static bool _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
    ffi.Pointer<objc.ObjCObjectImpl> arg1,
    ffi.Pointer<objc.ObjCObjectImpl> arg2,
  ) =>
      (objc.getBlockClosure(block)
          as bool Function(
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<objc.ObjCObjectImpl>,
            ffi.Pointer<objc.ObjCObjectImpl>,
          ))(arg0, arg1, arg2);
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Bool Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<objc.ObjCObjectImpl>,
            )
          >(_closureTrampoline, false)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.Bool Function(ffi.Pointer<ffi.Void>, UIGestureRecognizer, imp$1.UITouch)>`.
extension ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UITouch$CallExtension
    on
        objc.ObjCBlock<
          ffi.Bool Function(
            ffi.Pointer<ffi.Void>,
            UIGestureRecognizer,
            imp$1.UITouch,
          )
        > {
  bool call(
    ffi.Pointer<ffi.Void> arg0,
    UIGestureRecognizer arg1,
    imp$1.UITouch arg2,
  ) => ref.pointer.ref.invoke
      .cast<
        ffi.NativeFunction<
          ffi.Bool Function(
            ffi.Pointer<objc.ObjCBlockImpl> block,
            ffi.Pointer<ffi.Void> arg0,
            ffi.Pointer<objc.ObjCObjectImpl> arg1,
            ffi.Pointer<objc.ObjCObjectImpl> arg2,
          )
        >
      >()
      .asFunction<
        bool Function(
          ffi.Pointer<objc.ObjCBlockImpl>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >()(ref.pointer, arg0, arg1.ref.pointer, arg2.ref.pointer);
}

extension type UIGestureRecognizer._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [UIGestureRecognizer] that points to the same underlying object as [other].
  UIGestureRecognizer.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal('UIGestureRecognizer', iOS: (false, (3, 2, 0)));
    assert(isA(object$));
  }

  /// Constructs a [UIGestureRecognizer] that wraps the given raw object pointer.
  UIGestureRecognizer.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal('UIGestureRecognizer', iOS: (false, (3, 2, 0)));
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [UIGestureRecognizer].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_UIGestureRecognizer,
        );

  static UIGestureRecognizer alloc() {
    final $ret = _objc_msgSend_b5i7vq(_class_UIGestureRecognizer, _sel_alloc);
    return UIGestureRecognizer.fromPointer($ret, retain: false, release: true);
  }

  static UIGestureRecognizer allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1w1b8zj(
      _class_UIGestureRecognizer,
      _sel_allocWithZone_,
      zone,
    );
    return UIGestureRecognizer.fromPointer($ret, retain: false, release: true);
  }

  static UIGestureRecognizer new$() {
    final $ret = _objc_msgSend_b5i7vq(_class_UIGestureRecognizer, _sel_new);
    return UIGestureRecognizer.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of UIGestureRecognizer constructed with the default `new` method.
  UIGestureRecognizer() : this.as(new$());
}

extension UIGestureRecognizer$Methods on UIGestureRecognizer {
  void addTarget(
    objc.ObjCObject target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.addTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_wxleqh(
      object$.ref.pointer,
      _sel_addTarget_action_,
      target.ref.pointer,
      action,
    );
  }

  objc.NSArray get allowedPressTypes {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.allowedPressTypes',
      iOS: (false, (9, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_allowedPressTypes,
    );
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  objc.NSArray get allowedTouchTypes {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.allowedTouchTypes',
      iOS: (false, (9, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_allowedTouchTypes,
    );
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  int get buttonMask {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.buttonMask',
      iOS: (false, (13, 4, 0)),
    );
    return _objc_msgSend_1q9qz9z(object$.ref.pointer, _sel_buttonMask);
  }

  bool get cancelsTouchesInView {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.cancelsTouchesInView',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_7utsvh(object$.ref.pointer, _sel_cancelsTouchesInView);
  }

  bool get delaysTouchesBegan {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.delaysTouchesBegan',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_7utsvh(object$.ref.pointer, _sel_delaysTouchesBegan);
  }

  bool get delaysTouchesEnded {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.delaysTouchesEnded',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_7utsvh(object$.ref.pointer, _sel_delaysTouchesEnded);
  }

  UIGestureRecognizerDelegate? get delegate {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.delegate',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(object$.ref.pointer, _sel_delegate);
    return $ret.address == 0
        ? null
        : UIGestureRecognizerDelegate.fromPointer(
            $ret,
            retain: true,
            release: true,
          );
  }

  UIGestureRecognizer init() {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_b5i7vq(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return UIGestureRecognizer.fromPointer($ret, retain: false, release: true);
  }

  UIGestureRecognizer initWithCoder(objc.NSCoder coder) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.initWithCoder:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_s18bu6(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithCoder_,
      coder.ref.pointer,
    );
    return UIGestureRecognizer.fromPointer($ret, retain: false, release: true);
  }

  UIGestureRecognizer initWithTarget(
    objc.ObjCObject? target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.initWithTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_zimmlm(
      object$.ref.retainAndReturnPointer(),
      _sel_initWithTarget_action_,
      target?.ref.pointer ?? ffi.nullptr,
      action,
    );
    return UIGestureRecognizer.fromPointer($ret, retain: false, release: true);
  }

  bool get isEnabled {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.isEnabled',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_7utsvh(object$.ref.pointer, _sel_isEnabled);
  }

  objc.CGPoint locationInView(imp$1.UIView? view) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.locationInView:',
      iOS: (false, (3, 2, 0)),
    );
    final $ptr = pkg_ffi.calloc<objc.CGPoint>();
    objc.useMsgSendVariants
        ? _objc_msgSend_114acgxStret(
            $ptr,
            object$.ref.pointer,
            _sel_locationInView_,
            view?.ref.pointer ?? ffi.nullptr,
          )
        : $ptr.ref = _objc_msgSend_114acgx(
            object$.ref.pointer,
            _sel_locationInView_,
            view?.ref.pointer ?? ffi.nullptr,
          );
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<objc.CGPoint>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<objc.CGPoint>($finalizable);
  }

  objc.CGPoint locationOfTouch(int touchIndex, {imp$1.UIView? inView}) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.locationOfTouch:inView:',
      iOS: (false, (3, 2, 0)),
    );
    final $ptr = pkg_ffi.calloc<objc.CGPoint>();
    objc.useMsgSendVariants
        ? _objc_msgSend_nzlgnpStret(
            $ptr,
            object$.ref.pointer,
            _sel_locationOfTouch_inView_,
            touchIndex,
            inView?.ref.pointer ?? ffi.nullptr,
          )
        : $ptr.ref = _objc_msgSend_nzlgnp(
            object$.ref.pointer,
            _sel_locationOfTouch_inView_,
            touchIndex,
            inView?.ref.pointer ?? ffi.nullptr,
          );
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<objc.CGPoint>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<objc.CGPoint>($finalizable);
  }

  int get modifierFlags {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.modifierFlags',
      iOS: (false, (13, 4, 0)),
    );
    return _objc_msgSend_1q9qz9z(object$.ref.pointer, _sel_modifierFlags);
  }

  objc.NSString? get name {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.name',
      iOS: (false, (11, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(object$.ref.pointer, _sel_name);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  int get numberOfTouches {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.numberOfTouches',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_84sea1(object$.ref.pointer, _sel_numberOfTouches);
  }

  void removeTarget(
    objc.ObjCObject? target, {
    required ffi.Pointer<objc.ObjCSelector> action,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.removeTarget:action:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_wxleqh(
      object$.ref.pointer,
      _sel_removeTarget_action_,
      target?.ref.pointer ?? ffi.nullptr,
      action,
    );
  }

  void requireGestureRecognizerToFail(
    UIGestureRecognizer otherGestureRecognizer,
  ) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.requireGestureRecognizerToFail:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_requireGestureRecognizerToFail_,
      otherGestureRecognizer.ref.pointer,
    );
  }

  bool get requiresExclusiveTouchType {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.requiresExclusiveTouchType',
      iOS: (false, (9, 2, 0)),
    );
    return _objc_msgSend_7utsvh(
      object$.ref.pointer,
      _sel_requiresExclusiveTouchType,
    );
  }

  set allowedPressTypes(objc.NSArray value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setAllowedPressTypes:',
      iOS: (false, (9, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setAllowedPressTypes_,
      value.ref.pointer,
    );
  }

  set allowedTouchTypes(objc.NSArray value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setAllowedTouchTypes:',
      iOS: (false, (9, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setAllowedTouchTypes_,
      value.ref.pointer,
    );
  }

  set cancelsTouchesInView(bool value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setCancelsTouchesInView:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_68r7jb(
      object$.ref.pointer,
      _sel_setCancelsTouchesInView_,
      value,
    );
  }

  set delaysTouchesBegan(bool value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setDelaysTouchesBegan:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_68r7jb(
      object$.ref.pointer,
      _sel_setDelaysTouchesBegan_,
      value,
    );
  }

  set delaysTouchesEnded(bool value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setDelaysTouchesEnded:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_68r7jb(
      object$.ref.pointer,
      _sel_setDelaysTouchesEnded_,
      value,
    );
  }

  set delegate(UIGestureRecognizerDelegate? value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setDelegate:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setDelegate_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }

  set isEnabled(bool value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setEnabled:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_68r7jb(object$.ref.pointer, _sel_setEnabled_, value);
  }

  set name(objc.NSString? value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setName:',
      iOS: (false, (11, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setName_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }

  set requiresExclusiveTouchType(bool value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setRequiresExclusiveTouchType:',
      iOS: (false, (9, 2, 0)),
    );
    _objc_msgSend_68r7jb(
      object$.ref.pointer,
      _sel_setRequiresExclusiveTouchType_,
      value,
    );
  }

  imp$1.UIGestureRecognizerState get state {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.state',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_1hxg9b2(object$.ref.pointer, _sel_state);
    return imp$1.UIGestureRecognizerState.fromValue($ret);
  }

  imp$1.UIView? get view {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.view',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(object$.ref.pointer, _sel_view);
    return $ret.address == 0
        ? null
        : imp$1.UIView.fromPointer($ret, retain: true, release: true);
  }
}

extension type UIGestureRecognizerDelegate._(objc.ObjCProtocol object$)
    implements objc.ObjCProtocol, objc.NSObjectProtocol {
  /// Constructs a [UIGestureRecognizerDelegate] that points to the same underlying object as [other].
  UIGestureRecognizerDelegate.as(objc.ObjCObject other) : object$ = other;

  /// Constructs a [UIGestureRecognizerDelegate] that wraps the given raw object pointer.
  UIGestureRecognizerDelegate.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCProtocol(other, retain: retain, release: release);

  /// Returns whether [obj] is an instance of [UIGestureRecognizerDelegate].
  static bool conformsTo(objc.ObjCObject obj) {
    return _objc_msgSend_rvdyxc(
      obj.ref.pointer,
      _sel_conformsToProtocol_,
      _protocol_UIGestureRecognizerDelegate,
    );
  }
}

extension UIGestureRecognizerDelegate$Methods on UIGestureRecognizerDelegate {
  bool gestureRecognizerShouldBeRequiredToFailByGestureRecognizer(
    UIGestureRecognizer gestureRecognizer, {
    required UIGestureRecognizer shouldBeRequiredToFailByGestureRecognizer,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizerDelegate.gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:',
      iOS: (false, (7, 0, 0)),
    );
    if (!objc.respondsToSelector(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_,
    )) {
      throw objc.UnimplementedOptionalMethodException(
        'UIGestureRecognizerDelegate',
        'gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:',
      );
    }
    return _objc_msgSend_13ue5rx(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_,
      gestureRecognizer.ref.pointer,
      shouldBeRequiredToFailByGestureRecognizer.ref.pointer,
    );
  }

  bool gestureRecognizerShouldReceiveEvent(
    UIGestureRecognizer gestureRecognizer, {
    required imp$1.UIEvent shouldReceiveEvent,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizerDelegate.gestureRecognizer:shouldReceiveEvent:',
      iOS: (false, (13, 4, 0)),
    );
    if (!objc.respondsToSelector(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldReceiveEvent_,
    )) {
      throw objc.UnimplementedOptionalMethodException(
        'UIGestureRecognizerDelegate',
        'gestureRecognizer:shouldReceiveEvent:',
      );
    }
    return _objc_msgSend_13ue5rx(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldReceiveEvent_,
      gestureRecognizer.ref.pointer,
      shouldReceiveEvent.ref.pointer,
    );
  }

  bool gestureRecognizerShouldReceivePress(
    UIGestureRecognizer gestureRecognizer, {
    required imp$1.UIPress shouldReceivePress,
  }) {
    if (!objc.respondsToSelector(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldReceivePress_,
    )) {
      throw objc.UnimplementedOptionalMethodException(
        'UIGestureRecognizerDelegate',
        'gestureRecognizer:shouldReceivePress:',
      );
    }
    return _objc_msgSend_13ue5rx(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldReceivePress_,
      gestureRecognizer.ref.pointer,
      shouldReceivePress.ref.pointer,
    );
  }

  bool gestureRecognizerShouldReceiveTouch(
    UIGestureRecognizer gestureRecognizer, {
    required imp$1.UITouch shouldReceiveTouch,
  }) {
    if (!objc.respondsToSelector(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldReceiveTouch_,
    )) {
      throw objc.UnimplementedOptionalMethodException(
        'UIGestureRecognizerDelegate',
        'gestureRecognizer:shouldReceiveTouch:',
      );
    }
    return _objc_msgSend_13ue5rx(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldReceiveTouch_,
      gestureRecognizer.ref.pointer,
      shouldReceiveTouch.ref.pointer,
    );
  }

  bool gestureRecognizerShouldRecognizeSimultaneouslyWithGestureRecognizer(
    UIGestureRecognizer gestureRecognizer, {
    required UIGestureRecognizer
    shouldRecognizeSimultaneouslyWithGestureRecognizer,
  }) {
    if (!objc.respondsToSelector(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_,
    )) {
      throw objc.UnimplementedOptionalMethodException(
        'UIGestureRecognizerDelegate',
        'gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:',
      );
    }
    return _objc_msgSend_13ue5rx(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_,
      gestureRecognizer.ref.pointer,
      shouldRecognizeSimultaneouslyWithGestureRecognizer.ref.pointer,
    );
  }

  bool gestureRecognizerShouldRequireFailureOfGestureRecognizer(
    UIGestureRecognizer gestureRecognizer, {
    required UIGestureRecognizer shouldRequireFailureOfGestureRecognizer,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizerDelegate.gestureRecognizer:shouldRequireFailureOfGestureRecognizer:',
      iOS: (false, (7, 0, 0)),
    );
    if (!objc.respondsToSelector(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldRequireFailureOfGestureRecognizer_,
    )) {
      throw objc.UnimplementedOptionalMethodException(
        'UIGestureRecognizerDelegate',
        'gestureRecognizer:shouldRequireFailureOfGestureRecognizer:',
      );
    }
    return _objc_msgSend_13ue5rx(
      object$.ref.pointer,
      _sel_gestureRecognizer_shouldRequireFailureOfGestureRecognizer_,
      gestureRecognizer.ref.pointer,
      shouldRequireFailureOfGestureRecognizer.ref.pointer,
    );
  }

  bool gestureRecognizerShouldBegin(UIGestureRecognizer gestureRecognizer) {
    if (!objc.respondsToSelector(
      object$.ref.pointer,
      _sel_gestureRecognizerShouldBegin_,
    )) {
      throw objc.UnimplementedOptionalMethodException(
        'UIGestureRecognizerDelegate',
        'gestureRecognizerShouldBegin:',
      );
    }
    return _objc_msgSend_xat5dx(
      object$.ref.pointer,
      _sel_gestureRecognizerShouldBegin_,
      gestureRecognizer.ref.pointer,
    );
  }
}

abstract interface class UIGestureRecognizerDelegateSpec {}

abstract interface class UIGestureRecognizerDelegateOptional {
  bool gestureRecognizerShouldBeRequiredToFailByGestureRecognizer(
    UIGestureRecognizer gestureRecognizer, {
    required UIGestureRecognizer shouldBeRequiredToFailByGestureRecognizer,
  });
  bool gestureRecognizerShouldReceiveEvent(
    UIGestureRecognizer gestureRecognizer, {
    required imp$1.UIEvent shouldReceiveEvent,
  });
  bool gestureRecognizerShouldReceivePress(
    UIGestureRecognizer gestureRecognizer, {
    required imp$1.UIPress shouldReceivePress,
  });
  bool gestureRecognizerShouldReceiveTouch(
    UIGestureRecognizer gestureRecognizer, {
    required imp$1.UITouch shouldReceiveTouch,
  });
  bool gestureRecognizerShouldRecognizeSimultaneouslyWithGestureRecognizer(
    UIGestureRecognizer gestureRecognizer, {
    required UIGestureRecognizer
    shouldRecognizeSimultaneouslyWithGestureRecognizer,
  });
  bool gestureRecognizerShouldRequireFailureOfGestureRecognizer(
    UIGestureRecognizer gestureRecognizer, {
    required UIGestureRecognizer shouldRequireFailureOfGestureRecognizer,
  });
  bool gestureRecognizerShouldBegin(UIGestureRecognizer gestureRecognizer);
}

mixin UIGestureRecognizerDelegateDefaults
    implements UIGestureRecognizerDelegateOptional {
  @override
  dynamic noSuchMethod(Invocation invocation) => super.noSuchMethod(invocation);
}

interface class UIGestureRecognizerDelegate$Builder {
  /// Returns the [objc.Protocol] object for this protocol.
  static objc.Protocol get $protocol =>
      objc.Protocol.fromPointer(_protocol_UIGestureRecognizerDelegate.cast());

  /// Builds an object that implements the UIGestureRecognizerDelegate protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly.
  ///
  /// If `$keepIsolateAlive` is true, this protocol will keep this isolate
  /// alive until it is garbage collected by both Dart and ObjC.
  static UIGestureRecognizerDelegate implement({
    bool Function(UIGestureRecognizer, UIGestureRecognizer)?
    gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_,
    bool Function(UIGestureRecognizer, imp$1.UIEvent)?
    gestureRecognizer_shouldReceiveEvent_,
    bool Function(UIGestureRecognizer, imp$1.UIPress)?
    gestureRecognizer_shouldReceivePress_,
    bool Function(UIGestureRecognizer, imp$1.UITouch)?
    gestureRecognizer_shouldReceiveTouch_,
    bool Function(UIGestureRecognizer, UIGestureRecognizer)?
    gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_,
    bool Function(UIGestureRecognizer, UIGestureRecognizer)?
    gestureRecognizer_shouldRequireFailureOfGestureRecognizer_,
    bool Function(UIGestureRecognizer)? gestureRecognizerShouldBegin_,
    bool $keepIsolateAlive = true,
  }) {
    final builder = objc.ObjCProtocolBuilder(
      debugName: 'UIGestureRecognizerDelegate',
    );
    UIGestureRecognizerDelegate$Builder
        .gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_
        .implement(
          builder,
          gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_,
        );
    UIGestureRecognizerDelegate$Builder.gestureRecognizer_shouldReceiveEvent_
        .implement(builder, gestureRecognizer_shouldReceiveEvent_);
    UIGestureRecognizerDelegate$Builder.gestureRecognizer_shouldReceivePress_
        .implement(builder, gestureRecognizer_shouldReceivePress_);
    UIGestureRecognizerDelegate$Builder.gestureRecognizer_shouldReceiveTouch_
        .implement(builder, gestureRecognizer_shouldReceiveTouch_);
    UIGestureRecognizerDelegate$Builder
        .gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_
        .implement(
          builder,
          gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_,
        );
    UIGestureRecognizerDelegate$Builder
        .gestureRecognizer_shouldRequireFailureOfGestureRecognizer_
        .implement(
          builder,
          gestureRecognizer_shouldRequireFailureOfGestureRecognizer_,
        );
    UIGestureRecognizerDelegate$Builder.gestureRecognizerShouldBegin_.implement(
      builder,
      gestureRecognizerShouldBegin_,
    );
    builder.addProtocol($protocol);
    return UIGestureRecognizerDelegate.as(
      builder.build(keepIsolateAlive: $keepIsolateAlive),
    );
  }

  /// Adds the implementation of the UIGestureRecognizerDelegate protocol to an existing
  /// [objc.ObjCProtocolBuilder].
  ///
  /// Note: You cannot call this method after you have called `builder.build`.
  static void addToBuilder(
    objc.ObjCProtocolBuilder builder, {
    bool Function(UIGestureRecognizer, UIGestureRecognizer)?
    gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_,
    bool Function(UIGestureRecognizer, imp$1.UIEvent)?
    gestureRecognizer_shouldReceiveEvent_,
    bool Function(UIGestureRecognizer, imp$1.UIPress)?
    gestureRecognizer_shouldReceivePress_,
    bool Function(UIGestureRecognizer, imp$1.UITouch)?
    gestureRecognizer_shouldReceiveTouch_,
    bool Function(UIGestureRecognizer, UIGestureRecognizer)?
    gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_,
    bool Function(UIGestureRecognizer, UIGestureRecognizer)?
    gestureRecognizer_shouldRequireFailureOfGestureRecognizer_,
    bool Function(UIGestureRecognizer)? gestureRecognizerShouldBegin_,
    bool $keepIsolateAlive = true,
  }) {
    UIGestureRecognizerDelegate$Builder
        .gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_
        .implement(
          builder,
          gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_,
        );
    UIGestureRecognizerDelegate$Builder.gestureRecognizer_shouldReceiveEvent_
        .implement(builder, gestureRecognizer_shouldReceiveEvent_);
    UIGestureRecognizerDelegate$Builder.gestureRecognizer_shouldReceivePress_
        .implement(builder, gestureRecognizer_shouldReceivePress_);
    UIGestureRecognizerDelegate$Builder.gestureRecognizer_shouldReceiveTouch_
        .implement(builder, gestureRecognizer_shouldReceiveTouch_);
    UIGestureRecognizerDelegate$Builder
        .gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_
        .implement(
          builder,
          gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_,
        );
    UIGestureRecognizerDelegate$Builder
        .gestureRecognizer_shouldRequireFailureOfGestureRecognizer_
        .implement(
          builder,
          gestureRecognizer_shouldRequireFailureOfGestureRecognizer_,
        );
    UIGestureRecognizerDelegate$Builder.gestureRecognizerShouldBegin_.implement(
      builder,
      gestureRecognizerShouldBegin_,
    );
    builder.addProtocol($protocol);
  }

  /// Builds an object that implements the UIGestureRecognizerDelegate protocol using members
  /// from [implementation].
  ///
  /// Optional methods are only implemented when [implementation] also
  /// implements [UIGestureRecognizerDelegateOptional].
  static UIGestureRecognizerDelegate implementFrom(
    UIGestureRecognizerDelegateSpec implementation, {
    bool $keepIsolateAlive = true,
  }) {
    final UIGestureRecognizerDelegateOptional? optionalImplementation =
        implementation is UIGestureRecognizerDelegateOptional
        ? implementation as UIGestureRecognizerDelegateOptional
        : null;
    return implement(
      gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              UIGestureRecognizer shouldBeRequiredToFailByGestureRecognizer,
            ) => optionalImplementation
                .gestureRecognizerShouldBeRequiredToFailByGestureRecognizer(
                  gestureRecognizer,
                  shouldBeRequiredToFailByGestureRecognizer:
                      shouldBeRequiredToFailByGestureRecognizer,
                )
          : null,
      gestureRecognizer_shouldReceiveEvent_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldReceiveEvent_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              imp$1.UIEvent shouldReceiveEvent,
            ) => optionalImplementation.gestureRecognizerShouldReceiveEvent(
              gestureRecognizer,
              shouldReceiveEvent: shouldReceiveEvent,
            )
          : null,
      gestureRecognizer_shouldReceivePress_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldReceivePress_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              imp$1.UIPress shouldReceivePress,
            ) => optionalImplementation.gestureRecognizerShouldReceivePress(
              gestureRecognizer,
              shouldReceivePress: shouldReceivePress,
            )
          : null,
      gestureRecognizer_shouldReceiveTouch_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldReceiveTouch_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              imp$1.UITouch shouldReceiveTouch,
            ) => optionalImplementation.gestureRecognizerShouldReceiveTouch(
              gestureRecognizer,
              shouldReceiveTouch: shouldReceiveTouch,
            )
          : null,
      gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              UIGestureRecognizer
              shouldRecognizeSimultaneouslyWithGestureRecognizer,
            ) => optionalImplementation
                .gestureRecognizerShouldRecognizeSimultaneouslyWithGestureRecognizer(
                  gestureRecognizer,
                  shouldRecognizeSimultaneouslyWithGestureRecognizer:
                      shouldRecognizeSimultaneouslyWithGestureRecognizer,
                )
          : null,
      gestureRecognizer_shouldRequireFailureOfGestureRecognizer_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldRequireFailureOfGestureRecognizer_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              UIGestureRecognizer shouldRequireFailureOfGestureRecognizer,
            ) => optionalImplementation
                .gestureRecognizerShouldRequireFailureOfGestureRecognizer(
                  gestureRecognizer,
                  shouldRequireFailureOfGestureRecognizer:
                      shouldRequireFailureOfGestureRecognizer,
                )
          : null,
      gestureRecognizerShouldBegin_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizerShouldBegin_
                  .isAvailable &&
              optionalImplementation != null
          ? (UIGestureRecognizer gestureRecognizer) => optionalImplementation
                .gestureRecognizerShouldBegin(gestureRecognizer)
          : null,
      $keepIsolateAlive: $keepIsolateAlive,
    );
  }

  /// Adds an implementation of the UIGestureRecognizerDelegate protocol to an existing
  /// [objc.ObjCProtocolBuilder] using members from [implementation].
  static void addToBuilderFrom(
    objc.ObjCProtocolBuilder builder,
    UIGestureRecognizerDelegateSpec implementation,
  ) {
    final UIGestureRecognizerDelegateOptional? optionalImplementation =
        implementation is UIGestureRecognizerDelegateOptional
        ? implementation as UIGestureRecognizerDelegateOptional
        : null;
    addToBuilder(
      builder,
      gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              UIGestureRecognizer shouldBeRequiredToFailByGestureRecognizer,
            ) => optionalImplementation
                .gestureRecognizerShouldBeRequiredToFailByGestureRecognizer(
                  gestureRecognizer,
                  shouldBeRequiredToFailByGestureRecognizer:
                      shouldBeRequiredToFailByGestureRecognizer,
                )
          : null,
      gestureRecognizer_shouldReceiveEvent_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldReceiveEvent_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              imp$1.UIEvent shouldReceiveEvent,
            ) => optionalImplementation.gestureRecognizerShouldReceiveEvent(
              gestureRecognizer,
              shouldReceiveEvent: shouldReceiveEvent,
            )
          : null,
      gestureRecognizer_shouldReceivePress_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldReceivePress_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              imp$1.UIPress shouldReceivePress,
            ) => optionalImplementation.gestureRecognizerShouldReceivePress(
              gestureRecognizer,
              shouldReceivePress: shouldReceivePress,
            )
          : null,
      gestureRecognizer_shouldReceiveTouch_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldReceiveTouch_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              imp$1.UITouch shouldReceiveTouch,
            ) => optionalImplementation.gestureRecognizerShouldReceiveTouch(
              gestureRecognizer,
              shouldReceiveTouch: shouldReceiveTouch,
            )
          : null,
      gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              UIGestureRecognizer
              shouldRecognizeSimultaneouslyWithGestureRecognizer,
            ) => optionalImplementation
                .gestureRecognizerShouldRecognizeSimultaneouslyWithGestureRecognizer(
                  gestureRecognizer,
                  shouldRecognizeSimultaneouslyWithGestureRecognizer:
                      shouldRecognizeSimultaneouslyWithGestureRecognizer,
                )
          : null,
      gestureRecognizer_shouldRequireFailureOfGestureRecognizer_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizer_shouldRequireFailureOfGestureRecognizer_
                  .isAvailable &&
              optionalImplementation != null
          ? (
              UIGestureRecognizer gestureRecognizer,
              UIGestureRecognizer shouldRequireFailureOfGestureRecognizer,
            ) => optionalImplementation
                .gestureRecognizerShouldRequireFailureOfGestureRecognizer(
                  gestureRecognizer,
                  shouldRequireFailureOfGestureRecognizer:
                      shouldRequireFailureOfGestureRecognizer,
                )
          : null,
      gestureRecognizerShouldBegin_:
          UIGestureRecognizerDelegate$Builder
                  .gestureRecognizerShouldBegin_
                  .isAvailable &&
              optionalImplementation != null
          ? (UIGestureRecognizer gestureRecognizer) => optionalImplementation
                .gestureRecognizerShouldBegin(gestureRecognizer)
          : null,
    );
  }

  static final gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_ =
      objc.ObjCProtocolMethod<
        bool Function(UIGestureRecognizer, UIGestureRecognizer)
      >(
        _protocol_UIGestureRecognizerDelegate,
        _sel_gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Bool Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                )
              >
            >(_1ogluep_protocolTrampoline_2n06mv)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_UIGestureRecognizerDelegate,
          _sel_gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_,
          isRequired: false,
          isInstanceMethod: true,
        ),
        (bool Function(UIGestureRecognizer, UIGestureRecognizer) func) =>
            ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIGestureRecognizer.fromFunction(
              (
                ffi.Pointer<ffi.Void> _,
                UIGestureRecognizer arg1,
                UIGestureRecognizer arg2,
              ) => func(arg1, arg2),
            ),
      );
  static final gestureRecognizer_shouldReceiveEvent_ =
      objc.ObjCProtocolMethod<
        bool Function(UIGestureRecognizer, imp$1.UIEvent)
      >(
        _protocol_UIGestureRecognizerDelegate,
        _sel_gestureRecognizer_shouldReceiveEvent_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Bool Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                )
              >
            >(_1ogluep_protocolTrampoline_2n06mv)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_UIGestureRecognizerDelegate,
          _sel_gestureRecognizer_shouldReceiveEvent_,
          isRequired: false,
          isInstanceMethod: true,
        ),
        (bool Function(UIGestureRecognizer, imp$1.UIEvent) func) =>
            ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIEvent.fromFunction(
              (
                ffi.Pointer<ffi.Void> _,
                UIGestureRecognizer arg1,
                imp$1.UIEvent arg2,
              ) => func(arg1, arg2),
            ),
      );
  static final gestureRecognizer_shouldReceivePress_ =
      objc.ObjCProtocolMethod<
        bool Function(UIGestureRecognizer, imp$1.UIPress)
      >(
        _protocol_UIGestureRecognizerDelegate,
        _sel_gestureRecognizer_shouldReceivePress_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Bool Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                )
              >
            >(_1ogluep_protocolTrampoline_2n06mv)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_UIGestureRecognizerDelegate,
          _sel_gestureRecognizer_shouldReceivePress_,
          isRequired: false,
          isInstanceMethod: true,
        ),
        (bool Function(UIGestureRecognizer, imp$1.UIPress) func) =>
            ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIPress.fromFunction(
              (
                ffi.Pointer<ffi.Void> _,
                UIGestureRecognizer arg1,
                imp$1.UIPress arg2,
              ) => func(arg1, arg2),
            ),
      );
  static final gestureRecognizer_shouldReceiveTouch_ =
      objc.ObjCProtocolMethod<
        bool Function(UIGestureRecognizer, imp$1.UITouch)
      >(
        _protocol_UIGestureRecognizerDelegate,
        _sel_gestureRecognizer_shouldReceiveTouch_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Bool Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                )
              >
            >(_1ogluep_protocolTrampoline_2n06mv)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_UIGestureRecognizerDelegate,
          _sel_gestureRecognizer_shouldReceiveTouch_,
          isRequired: false,
          isInstanceMethod: true,
        ),
        (bool Function(UIGestureRecognizer, imp$1.UITouch) func) =>
            ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UITouch.fromFunction(
              (
                ffi.Pointer<ffi.Void> _,
                UIGestureRecognizer arg1,
                imp$1.UITouch arg2,
              ) => func(arg1, arg2),
            ),
      );
  static final gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_ =
      objc.ObjCProtocolMethod<
        bool Function(UIGestureRecognizer, UIGestureRecognizer)
      >(
        _protocol_UIGestureRecognizerDelegate,
        _sel_gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Bool Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                )
              >
            >(_1ogluep_protocolTrampoline_2n06mv)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_UIGestureRecognizerDelegate,
          _sel_gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_,
          isRequired: false,
          isInstanceMethod: true,
        ),
        (bool Function(UIGestureRecognizer, UIGestureRecognizer) func) =>
            ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIGestureRecognizer.fromFunction(
              (
                ffi.Pointer<ffi.Void> _,
                UIGestureRecognizer arg1,
                UIGestureRecognizer arg2,
              ) => func(arg1, arg2),
            ),
      );
  static final gestureRecognizer_shouldRequireFailureOfGestureRecognizer_ =
      objc.ObjCProtocolMethod<
        bool Function(UIGestureRecognizer, UIGestureRecognizer)
      >(
        _protocol_UIGestureRecognizerDelegate,
        _sel_gestureRecognizer_shouldRequireFailureOfGestureRecognizer_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Bool Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                )
              >
            >(_1ogluep_protocolTrampoline_2n06mv)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_UIGestureRecognizerDelegate,
          _sel_gestureRecognizer_shouldRequireFailureOfGestureRecognizer_,
          isRequired: false,
          isInstanceMethod: true,
        ),
        (bool Function(UIGestureRecognizer, UIGestureRecognizer) func) =>
            ObjCBlock_bool_ffiVoid_UIGestureRecognizer_UIGestureRecognizer.fromFunction(
              (
                ffi.Pointer<ffi.Void> _,
                UIGestureRecognizer arg1,
                UIGestureRecognizer arg2,
              ) => func(arg1, arg2),
            ),
      );
  static final gestureRecognizerShouldBegin_ =
      objc.ObjCProtocolMethod<bool Function(UIGestureRecognizer)>(
        _protocol_UIGestureRecognizerDelegate,
        _sel_gestureRecognizerShouldBegin_,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.Bool Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                  ffi.Pointer<objc.ObjCObjectImpl>,
                )
              >
            >(_1ogluep_protocolTrampoline_3su7tt)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_UIGestureRecognizerDelegate,
          _sel_gestureRecognizerShouldBegin_,
          isRequired: false,
          isInstanceMethod: true,
        ),
        (bool Function(UIGestureRecognizer) func) =>
            ObjCBlock_bool_ffiVoid_UIGestureRecognizer.fromFunction(
              (ffi.Pointer<ffi.Void> _, UIGestureRecognizer arg1) => func(arg1),
            ),
      );
}

mixin UIGestureRecognizerDelegateAdapter {
  /// Lazily creates a native adapter for this Dart implementation.
  late final UIGestureRecognizerDelegate asUIGestureRecognizerDelegate =
      UIGestureRecognizerDelegate$Builder.implementFrom(
        this as UIGestureRecognizerDelegateSpec,
      );
}

extension UIGestureRecognizerProtected on UIGestureRecognizer {
  bool canBePreventedByGestureRecognizer(
    UIGestureRecognizer preventingGestureRecognizer,
  ) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.canBePreventedByGestureRecognizer:',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_xat5dx(
      object$.ref.pointer,
      _sel_canBePreventedByGestureRecognizer_,
      preventingGestureRecognizer.ref.pointer,
    );
  }

  bool canPreventGestureRecognizer(
    UIGestureRecognizer preventedGestureRecognizer,
  ) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.canPreventGestureRecognizer:',
      iOS: (false, (3, 2, 0)),
    );
    return _objc_msgSend_xat5dx(
      object$.ref.pointer,
      _sel_canPreventGestureRecognizer_,
      preventedGestureRecognizer.ref.pointer,
    );
  }

  void ignorePress(
    imp$1.UIPress button, {
    required imp$1.UIPressesEvent forEvent,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.ignorePress:forEvent:',
      iOS: (false, (9, 0, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_ignorePress_forEvent_,
      button.ref.pointer,
      forEvent.ref.pointer,
    );
  }

  void ignoreTouch(imp$1.UITouch touch, {required imp$1.UIEvent forEvent}) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.ignoreTouch:forEvent:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_ignoreTouch_forEvent_,
      touch.ref.pointer,
      forEvent.ref.pointer,
    );
  }

  void pressesBegan(
    objc.NSSet presses, {
    required imp$1.UIPressesEvent withEvent,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.pressesBegan:withEvent:',
      iOS: (false, (9, 0, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_pressesBegan_withEvent_,
      presses.ref.pointer,
      withEvent.ref.pointer,
    );
  }

  void pressesCancelled(
    objc.NSSet presses, {
    required imp$1.UIPressesEvent withEvent,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.pressesCancelled:withEvent:',
      iOS: (false, (9, 0, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_pressesCancelled_withEvent_,
      presses.ref.pointer,
      withEvent.ref.pointer,
    );
  }

  void pressesChanged(
    objc.NSSet presses, {
    required imp$1.UIPressesEvent withEvent,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.pressesChanged:withEvent:',
      iOS: (false, (9, 0, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_pressesChanged_withEvent_,
      presses.ref.pointer,
      withEvent.ref.pointer,
    );
  }

  void pressesEnded(
    objc.NSSet presses, {
    required imp$1.UIPressesEvent withEvent,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.pressesEnded:withEvent:',
      iOS: (false, (9, 0, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_pressesEnded_withEvent_,
      presses.ref.pointer,
      withEvent.ref.pointer,
    );
  }

  void reset() {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.reset',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_1hfer5h(object$.ref.pointer, _sel_reset);
  }

  set state$1(imp$1.UIGestureRecognizerState value) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.setState:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_13ph5zu(object$.ref.pointer, _sel_setState_, value.value);
  }

  bool shouldBeRequiredToFailByGestureRecognizer(
    UIGestureRecognizer otherGestureRecognizer,
  ) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.shouldBeRequiredToFailByGestureRecognizer:',
      iOS: (false, (7, 0, 0)),
    );
    return _objc_msgSend_xat5dx(
      object$.ref.pointer,
      _sel_shouldBeRequiredToFailByGestureRecognizer_,
      otherGestureRecognizer.ref.pointer,
    );
  }

  bool shouldReceiveEvent(imp$1.UIEvent event) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.shouldReceiveEvent:',
      iOS: (false, (13, 4, 0)),
    );
    return _objc_msgSend_xat5dx(
      object$.ref.pointer,
      _sel_shouldReceiveEvent_,
      event.ref.pointer,
    );
  }

  bool shouldRequireFailureOfGestureRecognizer(
    UIGestureRecognizer otherGestureRecognizer,
  ) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.shouldRequireFailureOfGestureRecognizer:',
      iOS: (false, (7, 0, 0)),
    );
    return _objc_msgSend_xat5dx(
      object$.ref.pointer,
      _sel_shouldRequireFailureOfGestureRecognizer_,
      otherGestureRecognizer.ref.pointer,
    );
  }

  imp$1.UIGestureRecognizerState get state$1 {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.state',
      iOS: (false, (3, 2, 0)),
    );
    final $ret = _objc_msgSend_1hxg9b2(object$.ref.pointer, _sel_state);
    return imp$1.UIGestureRecognizerState.fromValue($ret);
  }

  void touchesBegan(objc.NSSet touches, {required imp$1.UIEvent withEvent}) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.touchesBegan:withEvent:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_touchesBegan_withEvent_,
      touches.ref.pointer,
      withEvent.ref.pointer,
    );
  }

  void touchesCancelled(
    objc.NSSet touches, {
    required imp$1.UIEvent withEvent,
  }) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.touchesCancelled:withEvent:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_touchesCancelled_withEvent_,
      touches.ref.pointer,
      withEvent.ref.pointer,
    );
  }

  void touchesEnded(objc.NSSet touches, {required imp$1.UIEvent withEvent}) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.touchesEnded:withEvent:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_touchesEnded_withEvent_,
      touches.ref.pointer,
      withEvent.ref.pointer,
    );
  }

  void touchesEstimatedPropertiesUpdated(objc.NSSet touches) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.touchesEstimatedPropertiesUpdated:',
      iOS: (false, (9, 1, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_touchesEstimatedPropertiesUpdated_,
      touches.ref.pointer,
    );
  }

  void touchesMoved(objc.NSSet touches, {required imp$1.UIEvent withEvent}) {
    objc.checkOsVersionInternal(
      'UIGestureRecognizer.touchesMoved:withEvent:',
      iOS: (false, (3, 2, 0)),
    );
    _objc_msgSend_rna891(
      object$.ref.pointer,
      _sel_touchesMoved_withEvent_,
      touches.ref.pointer,
      withEvent.ref.pointer,
    );
  }
}

late final _class_UIGestureRecognizer = objc.getClass("UIGestureRecognizer");
final _objc_msgSend_114acgx = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        objc.CGPoint Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      objc.CGPoint Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_114acgxStret = objc.msgSendStretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.CGPoint>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.CGPoint>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_13ph5zu = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_13ue5rx = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1dfwsa3 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1h6563x = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1hfer5h = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1hxg9b2 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Long Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1q9qz9z = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Long Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1w1b8zj = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        imp$1.instancetype Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      imp$1.instancetype Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
final _objc_msgSend_68r7jb = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Bool,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        bool,
      )
    >();
final _objc_msgSend_7utsvh = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_84sea1 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.UnsignedLong Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_b5i7vq = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        imp$1.instancetype Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      imp$1.instancetype Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_nzlgnp = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        objc.CGPoint Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.UnsignedLong,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      objc.CGPoint Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_nzlgnpStret = objc.msgSendStretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.CGPoint>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.UnsignedLong,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.CGPoint>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_rna891 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_rvdyxc = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCProtocolImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCProtocolImpl>,
      )
    >();
final _objc_msgSend_s18bu6 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        imp$1.instancetype Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      imp$1.instancetype Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_wxleqh = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_xat5dx = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_zimmlm = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        imp$1.instancetype Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      imp$1.instancetype Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _protocol_UIGestureRecognizerDelegate = objc.getProtocol(
  "UIGestureRecognizerDelegate",
);
late final _sel_addTarget_action_ = objc.registerName("addTarget:action:");
late final _sel_alloc = objc.registerName("alloc");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
late final _sel_allowedPressTypes = objc.registerName("allowedPressTypes");
late final _sel_allowedTouchTypes = objc.registerName("allowedTouchTypes");
late final _sel_buttonMask = objc.registerName("buttonMask");
late final _sel_canBePreventedByGestureRecognizer_ = objc.registerName(
  "canBePreventedByGestureRecognizer:",
);
late final _sel_canPreventGestureRecognizer_ = objc.registerName(
  "canPreventGestureRecognizer:",
);
late final _sel_cancelsTouchesInView = objc.registerName(
  "cancelsTouchesInView",
);
late final _sel_conformsToProtocol_ = objc.registerName("conformsToProtocol:");
late final _sel_delaysTouchesBegan = objc.registerName("delaysTouchesBegan");
late final _sel_delaysTouchesEnded = objc.registerName("delaysTouchesEnded");
late final _sel_delegate = objc.registerName("delegate");
late final _sel_gestureRecognizerShouldBegin_ = objc.registerName(
  "gestureRecognizerShouldBegin:",
);
late final _sel_gestureRecognizer_shouldBeRequiredToFailByGestureRecognizer_ =
    objc.registerName(
      "gestureRecognizer:shouldBeRequiredToFailByGestureRecognizer:",
    );
late final _sel_gestureRecognizer_shouldReceiveEvent_ = objc.registerName(
  "gestureRecognizer:shouldReceiveEvent:",
);
late final _sel_gestureRecognizer_shouldReceivePress_ = objc.registerName(
  "gestureRecognizer:shouldReceivePress:",
);
late final _sel_gestureRecognizer_shouldReceiveTouch_ = objc.registerName(
  "gestureRecognizer:shouldReceiveTouch:",
);
late final _sel_gestureRecognizer_shouldRecognizeSimultaneouslyWithGestureRecognizer_ =
    objc.registerName(
      "gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer:",
    );
late final _sel_gestureRecognizer_shouldRequireFailureOfGestureRecognizer_ =
    objc.registerName(
      "gestureRecognizer:shouldRequireFailureOfGestureRecognizer:",
    );
late final _sel_ignorePress_forEvent_ = objc.registerName(
  "ignorePress:forEvent:",
);
late final _sel_ignoreTouch_forEvent_ = objc.registerName(
  "ignoreTouch:forEvent:",
);
late final _sel_init = objc.registerName("init");
late final _sel_initWithCoder_ = objc.registerName("initWithCoder:");
late final _sel_initWithTarget_action_ = objc.registerName(
  "initWithTarget:action:",
);
late final _sel_isEnabled = objc.registerName("isEnabled");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
late final _sel_locationInView_ = objc.registerName("locationInView:");
late final _sel_locationOfTouch_inView_ = objc.registerName(
  "locationOfTouch:inView:",
);
late final _sel_modifierFlags = objc.registerName("modifierFlags");
late final _sel_name = objc.registerName("name");
late final _sel_new = objc.registerName("new");
late final _sel_numberOfTouches = objc.registerName("numberOfTouches");
late final _sel_pressesBegan_withEvent_ = objc.registerName(
  "pressesBegan:withEvent:",
);
late final _sel_pressesCancelled_withEvent_ = objc.registerName(
  "pressesCancelled:withEvent:",
);
late final _sel_pressesChanged_withEvent_ = objc.registerName(
  "pressesChanged:withEvent:",
);
late final _sel_pressesEnded_withEvent_ = objc.registerName(
  "pressesEnded:withEvent:",
);
late final _sel_removeTarget_action_ = objc.registerName(
  "removeTarget:action:",
);
late final _sel_requireGestureRecognizerToFail_ = objc.registerName(
  "requireGestureRecognizerToFail:",
);
late final _sel_requiresExclusiveTouchType = objc.registerName(
  "requiresExclusiveTouchType",
);
late final _sel_reset = objc.registerName("reset");
late final _sel_setAllowedPressTypes_ = objc.registerName(
  "setAllowedPressTypes:",
);
late final _sel_setAllowedTouchTypes_ = objc.registerName(
  "setAllowedTouchTypes:",
);
late final _sel_setCancelsTouchesInView_ = objc.registerName(
  "setCancelsTouchesInView:",
);
late final _sel_setDelaysTouchesBegan_ = objc.registerName(
  "setDelaysTouchesBegan:",
);
late final _sel_setDelaysTouchesEnded_ = objc.registerName(
  "setDelaysTouchesEnded:",
);
late final _sel_setDelegate_ = objc.registerName("setDelegate:");
late final _sel_setEnabled_ = objc.registerName("setEnabled:");
late final _sel_setName_ = objc.registerName("setName:");
late final _sel_setRequiresExclusiveTouchType_ = objc.registerName(
  "setRequiresExclusiveTouchType:",
);
late final _sel_setState_ = objc.registerName("setState:");
late final _sel_shouldBeRequiredToFailByGestureRecognizer_ = objc.registerName(
  "shouldBeRequiredToFailByGestureRecognizer:",
);
late final _sel_shouldReceiveEvent_ = objc.registerName("shouldReceiveEvent:");
late final _sel_shouldRequireFailureOfGestureRecognizer_ = objc.registerName(
  "shouldRequireFailureOfGestureRecognizer:",
);
late final _sel_state = objc.registerName("state");
late final _sel_touchesBegan_withEvent_ = objc.registerName(
  "touchesBegan:withEvent:",
);
late final _sel_touchesCancelled_withEvent_ = objc.registerName(
  "touchesCancelled:withEvent:",
);
late final _sel_touchesEnded_withEvent_ = objc.registerName(
  "touchesEnded:withEvent:",
);
late final _sel_touchesEstimatedPropertiesUpdated_ = objc.registerName(
  "touchesEstimatedPropertiesUpdated:",
);
late final _sel_touchesMoved_withEvent_ = objc.registerName(
  "touchesMoved:withEvent:",
);
late final _sel_view = objc.registerName("view");
