import 'dart:io';

import 'package:ffigen/ffigen.dart';

final _frameworks = <String, _FrameworkSpec>{
  'foundation': const _FrameworkSpec(
    key: 'foundation',
    packageDir: 'objc-foundation',
    packageName: 'objc_foundation',
    framework: 'Foundation',
    umbrellaHeader: 'Foundation.h',
    dylibName: 'foundation_bindings.dylib',
    generatedBase: 'foundation',
    frameworkLoadOrder: ['Foundation'],
    sdk: _AppleSdk.macOS,
    runtimeFrameworkPaths: [
      '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation',
    ],
  ),
  'appkit': const _FrameworkSpec(
    key: 'appkit',
    packageDir: 'objc-appkit',
    packageName: 'objc_appkit',
    framework: 'AppKit',
    umbrellaHeader: 'AppKit.h',
    dylibName: 'appkit_bindings.dylib',
    generatedBase: 'appkit',
    frameworkLoadOrder: ['Foundation', 'AppKit'],
    sdk: _AppleSdk.macOS,
    runtimeFrameworkPaths: [
      '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation',
      '/System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit',
    ],
  ),
  'uikit': const _FrameworkSpec(
    key: 'uikit',
    packageDir: 'objc-uikit',
    packageName: 'objc_uikit',
    framework: 'UIKit',
    umbrellaHeader: 'UIKit.h',
    dylibName: 'uikit_bindings.dylib',
    generatedBase: 'uikit',
    frameworkLoadOrder: ['Foundation', 'UIKit'],
    sdk: _AppleSdk.iOSSimulator,
    runtimeFrameworkPaths: [
      '/System/Library/Frameworks/Foundation.framework/Foundation',
      '/System/Library/Frameworks/UIKit.framework/UIKit',
    ],
  ),
  'metal': const _FrameworkSpec(
    key: 'metal',
    packageDir: 'objc-metal',
    packageName: 'objc_metal',
    framework: 'Metal',
    umbrellaHeader: 'Metal.h',
    dylibName: 'metal_bindings.dylib',
    generatedBase: 'metal',
    frameworkLoadOrder: ['Foundation', 'Metal'],
    sdk: _AppleSdk.macOS,
    runtimeFrameworkPaths: [
      '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation',
      '/System/Library/Frameworks/Metal.framework/Versions/Current/Metal',
    ],
  ),
  'metalkit': const _FrameworkSpec(
    key: 'metalkit',
    packageDir: 'objc-metalkit',
    packageName: 'objc_metalkit',
    framework: 'MetalKit',
    umbrellaHeader: 'MetalKit.h',
    dylibName: 'metalkit_bindings.dylib',
    generatedBase: 'metalkit',
    frameworkLoadOrder: ['Foundation', 'Metal', 'MetalKit'],
    sdk: _AppleSdk.macOS,
    runtimeFrameworkPaths: [
      '/System/Library/Frameworks/Foundation.framework/Versions/Current/Foundation',
      '/System/Library/Frameworks/Metal.framework/Versions/Current/Metal',
      '/System/Library/Frameworks/MetalKit.framework/Versions/Current/MetalKit',
    ],
  ),
};

Future<void> main(List<String> args) async {
  final selected = _resolveTargets(args);
  final rootDir = Directory.current.absolute;
  final packagesDir = Directory('${rootDir.path}/packages');
  await packagesDir.create(recursive: true);

  for (final key in selected) {
    final spec = _frameworks[key]!;
    final sdkPath = _sdkPathFor(spec.sdk);
    final pkgDir = Directory('${packagesDir.path}/${spec.packageDir}');
    await _scaffoldPackage(spec, pkgDir);
    _generateBindings(spec, pkgDir, sdkPath);
    stdout.writeln('Generated ${spec.packageName} at ${pkgDir.path}');
  }
}

List<String> _resolveTargets(List<String> args) {
  if (args.isEmpty) {
    return _frameworks.keys.toList(growable: false);
  }
  final lowered = args.map((a) => a.toLowerCase()).toList(growable: false);
  for (final key in lowered) {
    if (!_frameworks.containsKey(key)) {
      stderr.writeln(
        'Unknown target "$key". Valid targets: ${_frameworks.keys.join(', ')}',
      );
      exitCode = 64;
      exit(exitCode);
    }
  }
  return lowered;
}

void _generateBindings(_FrameworkSpec spec, Directory pkgDir, String sdkPath) {
  final header = Uri.file(
    '$sdkPath/System/Library/Frameworks/${spec.framework}.framework/Headers/${spec.umbrellaHeader}',
  );
  final dartOut = Uri.file(
    '${pkgDir.path}/lib/src/${spec.generatedBase}_bindings.dart',
  );
  final objcOut = Uri.file(
    '${pkgDir.path}/native/${spec.generatedBase}_bindings.m',
  );

  final generator = FfiGenerator(
    headers: Headers(
      entryPoints: [header],
      compilerOptions: _compilerOptionsFor(spec, sdkPath),
      ignoreSourceErrors: true,
    ),
    objectiveC: _objectiveCConfig(spec),
    output: Output(
      dartFile: dartOut,
      objectiveCFile: objcOut,
      preamble:
          '// Full ${spec.framework} bindings generated by tool/gen_objc_packages.dart',
      style: _usesBundledBindingsAsset(spec)
          ? NativeExternalBindings(
              assetId:
                  'package:${spec.packageName}/${_bindingsAssetName(spec)}',
            )
          : const NativeExternalBindings(),
    ),
  );
  generator.generate();
}

List<String> _compilerOptionsFor(_FrameworkSpec spec, String sdkPath) {
  return ['-isysroot', sdkPath, '-F$sdkPath/System/Library/Frameworks'];
}

String _sdkPathFor(_AppleSdk sdk) {
  switch (sdk) {
    case _AppleSdk.macOS:
      return macSdkPath;
    case _AppleSdk.iOSSimulator:
      return _firstLineOfStdout('xcrun', [
        '--show-sdk-path',
        '--sdk',
        'iphonesimulator',
      ]);
  }
}

String _firstLineOfStdout(String command, List<String> args) {
  final result = Process.runSync(command, args);
  if (result.exitCode != 0) {
    throw ProcessException(
      command,
      args,
      '${result.stdout}${result.stderr}',
      result.exitCode,
    );
  }
  return (result.stdout as String)
      .split('\n')
      .firstWhere((line) => line.trim().isNotEmpty);
}

ObjectiveC _objectiveCConfig(_FrameworkSpec spec) {
  if (spec.key == 'metalkit') {
    bool includeMtk(Declaration decl) => decl.originalName.startsWith('MTK');
    return ObjectiveC(
      interfaces: Interfaces(include: includeMtk, includeTransitive: false),
      protocols: Protocols(include: includeMtk, includeTransitive: false),
      categories: Categories(include: includeMtk, includeTransitive: false),
    );
  }
  if (spec.key == 'appkit') {
    bool includeSubclassHelpers(Declaration decl) =>
        decl.originalName == 'NSViewController';
    return ObjectiveC(
      interfaces: Interfaces(
        include: Declarations.includeAll,
        includeTransitive: true,
        includeSubclassHelpers: includeSubclassHelpers,
      ),
      protocols: Protocols(
        include: Declarations.includeAll,
        includeTransitive: true,
      ),
      categories: Categories(
        include: Declarations.includeAll,
        includeTransitive: true,
      ),
    );
  }
  if (spec.key == 'uikit') {
    bool includeSubclassHelpers(Declaration decl) =>
        decl.originalName == 'UIViewController';
    bool includeMember(Declaration decl, String member) {
      if (decl.originalName == 'UIViewController' &&
          member == 'preferredContainerBackgroundStyle') {
        return false;
      }
      if (decl.originalName == 'CIImageProcessorKernel' &&
          (member == 'outputIsOpaque' || member == 'synchronizeInputs')) {
        return false;
      }
      return true;
    }

    return ObjectiveC(
      interfaces: Interfaces(
        include: Declarations.includeAll,
        includeTransitive: true,
        includeSubclassHelpers: includeSubclassHelpers,
        includeMember: includeMember,
      ),
      protocols: Protocols(
        include: Declarations.includeAll,
        includeTransitive: true,
      ),
      categories: Categories(
        include: Declarations.includeAll,
        includeTransitive: true,
      ),
    );
  }
  return const ObjectiveC(
    interfaces: Interfaces(
      include: Declarations.includeAll,
      includeTransitive: true,
    ),
    protocols: Protocols(
      include: Declarations.includeAll,
      includeTransitive: true,
    ),
    categories: Categories(
      include: Declarations.includeAll,
      includeTransitive: true,
    ),
  );
}

Future<void> _scaffoldPackage(_FrameworkSpec spec, Directory pkgDir) async {
  await Directory('${pkgDir.path}/lib/src').create(recursive: true);
  await Directory('${pkgDir.path}/native').create(recursive: true);
  await Directory('${pkgDir.path}/tool').create(recursive: true);
  if (_needsBuildHook(spec)) {
    await Directory('${pkgDir.path}/hook').create(recursive: true);
  }

  await File('${pkgDir.path}/pubspec.yaml').writeAsString(_pubspecFor(spec));
  await File(
    '${pkgDir.path}/analysis_options.yaml',
  ).writeAsString(_analysisOptions);
  await File('${pkgDir.path}/README.md').writeAsString(_readmeFor(spec));
  await File('${pkgDir.path}/.gitignore').writeAsString(_gitIgnore);
  await File(
    '${pkgDir.path}/lib/${spec.packageName}.dart',
  ).writeAsString(_libraryExports(spec));
  if (_hasFlutterViews(spec)) {
    await File(
      '${pkgDir.path}/lib/flutter_views.dart',
    ).writeAsString(_flutterViewsLibraryExports());
  }
  await File(
    '${pkgDir.path}/tool/generate.dart',
  ).writeAsString(_packageGenerateTool(spec));
  if (_needsBuildHook(spec)) {
    await File(
      '${pkgDir.path}/hook/build.dart',
    ).writeAsString(_buildHookFor(spec));
  }
}

String _pubspecFor(_FrameworkSpec spec) {
  final includeFlutterHelpers = _hasFlutterViews(spec);
  final includeBuildHookDeps = _needsBuildHook(spec);
  final extraDeps = includeBuildHookDeps
      ? '''
  code_assets: ^1.0.0
  hooks: ^1.0.0
  logging: ^1.3.0
  native_toolchain_c: ^0.17.4
${includeFlutterHelpers ? "  flutter:\n    sdk: flutter\n" : ''}'''
      : '';
  final dependencyOverrides = includeBuildHookDeps
      ? '''

dependency_overrides:
  code_assets:
    path: ../../ffigen/pkgs/code_assets
  hooks:
    path: ../../ffigen/pkgs/hooks
  native_toolchain_c:
    path: ../../ffigen/pkgs/native_toolchain_c
'''
      : '';
  return '''
name: ${spec.packageName}
description: Full Objective-C bindings for ${spec.framework}.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
$extraDeps  ffi: ^2.2.0
  objective_c:
    path: ../../ffigen/pkgs/objective_c

dev_dependencies:
  ffigen:
    path: ../../ffigen/pkgs/ffigen
  lints: ^6.0.0
$dependencyOverrides''';
}

const _analysisOptions = '''
include: package:lints/recommended.yaml
''';

String _libraryExports(_FrameworkSpec spec) {
  final buffer = StringBuffer()
    ..writeln("export 'src/${spec.generatedBase}_bindings.dart';");
  if (spec.key == 'appkit') {
    buffer.writeln("export 'src/target_action.dart';");
  }
  return buffer.toString();
}

String _flutterViewsLibraryExports() => "export 'src/flutter_views.dart';\n";

String _readmeFor(_FrameworkSpec spec) {
  final flutterHelpers = switch (spec.key) {
    'appkit' => '''

This package also bundles the Flutter platform-view transfer shim used by the
demo app:

- import `package:${spec.packageName}/flutter_views.dart`
- `registerObjCAppKitViewType(...)`
- `ObjCAppKitHostView`
''',
    'uikit' => '''

This package also bundles the Flutter platform-view transfer shim used by the
demo app:

- import `package:${spec.packageName}/flutter_views.dart`
- `registerObjCUiKitViewType(...)`
- `ObjCUiKitHostView`
''',
    _ => '',
  };
  return '''
# ${spec.packageName}

Generated Objective-C bindings for `${spec.framework}` using the local
`ffigen` fork in `../ffigen`.$flutterHelpers

## Regenerate

From the repository root:

```bash
dart run tool/gen_objc_packages.dart ${spec.key}
```

To regenerate all packages used by the demos:

```bash
dart run tool/gen_objc_packages.dart foundation appkit uikit metal metalkit
```
''';
}

String _packageGenerateTool(_FrameworkSpec spec) {
  return '''
import 'dart:io';

Future<void> main() async {
  final result = await Process.run(
    'dart',
    ['run', '../../tool/gen_objc_packages.dart', '${spec.key}'],
    runInShell: true,
  );
  stdout.write(result.stdout);
  stderr.write(result.stderr);
  exitCode = result.exitCode;
}
''';
}

const _gitIgnore = '''
.dart_tool/
build/
''';

bool _hasFlutterViews(_FrameworkSpec spec) =>
    spec.key == 'appkit' || spec.key == 'uikit';

bool _needsBuildHook(_FrameworkSpec spec) => _hasFlutterViews(spec);

bool _usesBundledBindingsAsset(_FrameworkSpec spec) =>
    spec.key == 'appkit' || spec.key == 'uikit';

String _bindingsAssetName(_FrameworkSpec spec) =>
    '${spec.packageName}_bindings.dylib';

String _supportedOsCheck(_FrameworkSpec spec) => switch (spec.key) {
  'appkit' => 'codeConfig.targetOS != OS.macOS',
  'uikit' => 'codeConfig.targetOS != OS.iOS',
  _ => 'true',
};

String _frameworkLinkFlags(_FrameworkSpec spec) => spec.frameworkLoadOrder
    .map((framework) => "      '-framework',\n      '$framework',")
    .join('\n');

String _buildHookFor(_FrameworkSpec spec) {
  final includeFlutterViews = _hasFlutterViews(spec);
  final includeBindingsAsset = _usesBundledBindingsAsset(spec);
  final bindingsBlock = includeBindingsAsset
      ? '''

    final bindingsAssetPath = input.outputDirectory.resolve(bindingsAssetName);
    final bindingsSrc =
        input.packageRoot.resolve('native/${spec.generatedBase}_bindings.m').toFilePath();
    final bindingsObject = await builder.buildObject(
      bindingsSrc,
      [...cFlags, ...objCFlags],
    );
    await builder.linkLib(bindingsObject, bindingsAssetPath.toFilePath(), [
      ...cFlags,
${_frameworkLinkFlags(spec)}
    ]);
    output.dependencies.add(Uri.file(bindingsSrc));
    output.assets.code.add(
      CodeAsset(
        package: input.packageName,
        name: bindingsAssetName,
        file: bindingsAssetPath,
        linkMode: DynamicLoadingBundled(),
      ),
    );
'''
      : '';
  final flutterViewsBlock = includeFlutterViews
      ? '''

    final flutterViewsAssetPath = input.outputDirectory.resolve(flutterViewsAssetName);
    final flutterViewsSrc = input.packageRoot.resolve('src/flutter_views.m').toFilePath();
    final flutterViewsObject = await builder.buildObject(
      flutterViewsSrc,
      [...cFlags, ...objCFlags],
    );
    await builder.linkLib(flutterViewsObject, flutterViewsAssetPath.toFilePath(), [
      ...cFlags,
${_frameworkLinkFlags(spec)}
    ]);
    output.dependencies.add(Uri.file(flutterViewsSrc));
    output.assets.code.add(
      CodeAsset(
        package: input.packageName,
        name: flutterViewsAssetName,
        file: flutterViewsAssetPath,
        linkMode: DynamicLoadingBundled(),
      ),
    );
'''
      : '';

  return '''
import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:logging/logging.dart';
import 'package:native_toolchain_c/src/cbuilder/compiler_resolver.dart';

const objCFlags = ['-x', 'objective-c', '-fobjc-arc'];
${includeBindingsAsset ? "const bindingsAssetName = '${_bindingsAssetName(spec)}';" : ''}
${includeFlutterViews ? "const flutterViewsAssetName = '${spec.packageName}_flutter_views.dylib';" : ''}

final logger = Logger('')
  ..level = Level.INFO
  ..onRecord.listen((record) {
    print('\${record.level.name}: \${record.time}: \${record.message}');
  });

void main(List<String> args) async {
  await build(args, (input, output) async {
    if (!input.config.buildCodeAssets) {
      return;
    }

    final codeConfig = input.config.code;
    if (${_supportedOsCheck(spec)}) {
      return;
    }

    if (codeConfig.linkModePreference == LinkModePreference.static) {
      throw UnsupportedError('LinkModePreference.static is not supported.');
    }

    final builder = await _Builder.create(
      input,
      input.packageRoot.toFilePath(),
    );
    final cFlags = <String>[
      '-isysroot',
      _sdkPath(codeConfig),
      '-target',
      _toTargetTriple(codeConfig),
      _minOsVersion(codeConfig),
    ];
$bindingsBlock
$flutterViewsBlock
  });
}

class _Builder {
  final String _compiler;
  final String _rootDir;
  final Uri _tempOutDir;

  _Builder._(this._compiler, this._rootDir, this._tempOutDir);

  static Future<_Builder> create(BuildInput input, String rootDir) async {
    final resolver = CompilerResolver(
      codeConfig: input.config.code,
      logger: logger,
    );
    return _Builder._(
      (await resolver.resolveCompiler()).uri.toFilePath(),
      rootDir,
      input.outputDirectory.resolve('obj/'),
    );
  }

  Future<String> buildObject(String input, List<String> flags) async {
    assert(input.startsWith(_rootDir));
    final relativeInput = input.substring(_rootDir.length);
    final output = '\${_tempOutDir.resolve(relativeInput).toFilePath()}.o';
    File(output).parent.createSync(recursive: true);
    await _compile([...flags, '-c', input, '-fpic'], output);
    return output;
  }

  Future<void> linkLib(String object, String output, List<String> flags) =>
      _compile([
        '-shared',
        '-Wl,-encryptable',
        '-undefined',
        'dynamic_lookup',
        ...flags,
        object,
      ], output);

  Future<void> _compile(List<String> flags, String output) async {
    final args = [...flags, '-o', output];
    logger.info('Running: \$_compiler \${args.join(" ")}');
    final proc = await Process.run(_compiler, args);
    logger.info(proc.stdout);
    logger.info(proc.stderr);
    if (proc.exitCode != 0) {
      exitCode = proc.exitCode;
      throw Exception('Command failed: \$_compiler \${args.join(" ")}');
    }
  }
}

String _sdkPath(CodeConfig codeConfig) {
  final sdk = switch (codeConfig.targetOS) {
    OS.iOS => codeConfig.iOS.targetSdk == IOSSdk.iPhoneOS
        ? 'iphoneos'
        : 'iphonesimulator',
    OS.macOS => 'macosx',
    _ => throw UnsupportedError('Unsupported target OS: \${codeConfig.targetOS}'),
  };
  return _firstLineOfStdout('xcrun', ['--show-sdk-path', '--sdk', sdk]);
}

String _firstLineOfStdout(String cmd, List<String> args) {
  final result = Process.runSync(cmd, args);
  assert(result.exitCode == 0);
  return (result.stdout as String)
      .split('\\n')
      .where((line) => line.isNotEmpty)
      .first;
}

String _minOsVersion(CodeConfig codeConfig) => switch (codeConfig.targetOS) {
  OS.iOS => '-mios-version-min=\${codeConfig.iOS.targetVersion}',
  OS.macOS => '-mmacos-version-min=\${codeConfig.macOS.targetVersion}',
  _ => throw UnsupportedError('Unsupported target OS: \${codeConfig.targetOS}'),
};

String _toTargetTriple(CodeConfig codeConfig) => switch (codeConfig.targetOS) {
  OS.iOS => _appleClangIosTargetFlags[codeConfig.targetArchitecture]![codeConfig.iOS.targetSdk]!,
  OS.macOS => _appleClangMacosTargetFlags[codeConfig.targetArchitecture]!,
  _ => throw UnsupportedError('Unsupported target OS: \${codeConfig.targetOS}'),
};

const _appleClangMacosTargetFlags = {
  Architecture.arm64: 'arm64-apple-darwin',
  Architecture.x64: 'x86_64-apple-darwin',
};

const _appleClangIosTargetFlags = {
  Architecture.arm64: {
    IOSSdk.iPhoneOS: 'arm64-apple-ios',
    IOSSdk.iPhoneSimulator: 'arm64-apple-ios-simulator',
  },
  Architecture.x64: {IOSSdk.iPhoneSimulator: 'x86_64-apple-ios-simulator'},
};
''';
}

class _FrameworkSpec {
  const _FrameworkSpec({
    required this.key,
    required this.packageDir,
    required this.packageName,
    required this.framework,
    required this.umbrellaHeader,
    required this.generatedBase,
    required this.dylibName,
    required this.frameworkLoadOrder,
    required this.sdk,
    required this.runtimeFrameworkPaths,
  });

  final String key;
  final String packageDir;
  final String packageName;
  final String framework;
  final String umbrellaHeader;
  final String generatedBase;
  final String dylibName;
  final List<String> frameworkLoadOrder;
  final _AppleSdk sdk;
  final List<String> runtimeFrameworkPaths;
}

enum _AppleSdk { macOS, iOSSimulator }
