// split Metal bindings generated by tool/gen_objc_packages.dart for objc_metal/metal_archive_base.
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

@ffi.Native<
  ffi.Pointer<objc.ObjCObjectImpl> Function(
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<ffi.Void>,
  )
>()
external ffi.Pointer<objc.ObjCObjectImpl> _114eave_protocolTrampoline_1mbt9g9(
  ffi.Pointer<objc.ObjCObjectImpl> target,
  ffi.Pointer<ffi.Void> sel,
);

@ffi.Native<
  ffi.UnsignedLong Function(
    ffi.Pointer<objc.ObjCObjectImpl>,
    ffi.Pointer<ffi.Void>,
  )
>()
external int _114eave_protocolTrampoline_srgf34(
  ffi.Pointer<objc.ObjCObjectImpl> target,
  ffi.Pointer<ffi.Void> sel,
);

extension type MTL4BinaryFunction._(objc.ObjCProtocol object$)
    implements objc.ObjCProtocol, objc.NSObjectProtocol {
  /// Constructs a [MTL4BinaryFunction] that points to the same underlying object as [other].
  MTL4BinaryFunction.as(objc.ObjCObject other) : object$ = other;

  /// Constructs a [MTL4BinaryFunction] that wraps the given raw object pointer.
  MTL4BinaryFunction.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCProtocol(other, retain: retain, release: release);

  /// Returns whether [obj] is an instance of [MTL4BinaryFunction].
  static bool conformsTo(objc.ObjCObject obj) {
    return _objc_msgSend_rvdyxc(
      obj.ref.pointer,
      _sel_conformsToProtocol_,
      _protocol_MTL4BinaryFunction,
    );
  }
}

extension MTL4BinaryFunction$Methods on MTL4BinaryFunction {
  MTLFunctionType get functionType {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunction.functionType',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_yjrosu(object$.ref.pointer, _sel_functionType);
    return MTLFunctionType.fromValue($ret);
  }

  objc.NSString? get name {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunction.name',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(object$.ref.pointer, _sel_name);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }
}

abstract interface class MTL4BinaryFunctionSpec {
  MTLFunctionType get functionType;
  objc.NSString? get name;
}

abstract interface class MTL4BinaryFunctionOptional {}

interface class MTL4BinaryFunction$Builder {
  /// Returns the [objc.Protocol] object for this protocol.
  static objc.Protocol get $protocol =>
      objc.Protocol.fromPointer(_protocol_MTL4BinaryFunction.cast());

  /// Builds an object that implements the MTL4BinaryFunction protocol. To implement
  /// multiple protocols, use [addToBuilder] or [objc.ObjCProtocolBuilder] directly.
  ///
  /// If `$keepIsolateAlive` is true, this protocol will keep this isolate
  /// alive until it is garbage collected by both Dart and ObjC.
  static MTL4BinaryFunction implement({
    required MTLFunctionType Function() functionType,
    required objc.NSString? Function() name,
    bool $keepIsolateAlive = true,
  }) {
    final builder = objc.ObjCProtocolBuilder(debugName: 'MTL4BinaryFunction');
    MTL4BinaryFunction$Builder.functionType.implement(builder, functionType);
    MTL4BinaryFunction$Builder.name.implement(builder, name);
    builder.addProtocol($protocol);
    return MTL4BinaryFunction.as(
      builder.build(keepIsolateAlive: $keepIsolateAlive),
    );
  }

  /// Adds the implementation of the MTL4BinaryFunction protocol to an existing
  /// [objc.ObjCProtocolBuilder].
  ///
  /// Note: You cannot call this method after you have called `builder.build`.
  static void addToBuilder(
    objc.ObjCProtocolBuilder builder, {
    required MTLFunctionType Function() functionType,
    required objc.NSString? Function() name,
    bool $keepIsolateAlive = true,
  }) {
    MTL4BinaryFunction$Builder.functionType.implement(builder, functionType);
    MTL4BinaryFunction$Builder.name.implement(builder, name);
    builder.addProtocol($protocol);
  }

  /// Builds an object that implements the MTL4BinaryFunction protocol using members
  /// from [implementation].
  ///
  /// Optional methods are only implemented when [implementation] also
  /// implements [MTL4BinaryFunctionOptional].
  static MTL4BinaryFunction implementFrom(
    MTL4BinaryFunctionSpec implementation, {
    bool $keepIsolateAlive = true,
  }) {
    return implement(
      functionType: () => implementation.functionType,
      name: () => implementation.name,
      $keepIsolateAlive: $keepIsolateAlive,
    );
  }

  /// Adds an implementation of the MTL4BinaryFunction protocol to an existing
  /// [objc.ObjCProtocolBuilder] using members from [implementation].
  static void addToBuilderFrom(
    objc.ObjCProtocolBuilder builder,
    MTL4BinaryFunctionSpec implementation,
  ) {
    addToBuilder(
      builder,
      functionType: () => implementation.functionType,
      name: () => implementation.name,
    );
  }

  static final functionType =
      objc.ObjCProtocolMethod<MTLFunctionType Function()>(
        _protocol_MTL4BinaryFunction,
        _sel_functionType,
        ffi.Native.addressOf<
              ffi.NativeFunction<
                ffi.UnsignedLong Function(
                  ffi.Pointer<objc.ObjCObjectImpl>,
                  ffi.Pointer<ffi.Void>,
                )
              >
            >(_114eave_protocolTrampoline_srgf34)
            .cast(),
        objc.getProtocolMethodSignature(
          _protocol_MTL4BinaryFunction,
          _sel_functionType,
          isRequired: true,
          isInstanceMethod: true,
        ),
        (MTLFunctionType Function() func) =>
            ObjCBlock_MTLFunctionType_ffiVoid.fromFunction(
              (ffi.Pointer<ffi.Void> _) => func(),
            ),
      );
  static final name = objc.ObjCProtocolMethod<objc.NSString? Function()>(
    _protocol_MTL4BinaryFunction,
    _sel_name,
    ffi.Native.addressOf<
          ffi.NativeFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCObjectImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >
        >(_114eave_protocolTrampoline_1mbt9g9)
        .cast(),
    objc.getProtocolMethodSignature(
      _protocol_MTL4BinaryFunction,
      _sel_name,
      isRequired: true,
      isInstanceMethod: true,
    ),
    (objc.NSString? Function() func) => ObjCBlock_NSString_ffiVoid.fromFunction(
      (ffi.Pointer<ffi.Void> _) => func(),
    ),
  );
}

mixin MTL4BinaryFunctionAdapter {
  /// Lazily creates a native adapter for this Dart implementation.
  late final MTL4BinaryFunction asMTL4BinaryFunction =
      MTL4BinaryFunction$Builder.implementFrom(this as MTL4BinaryFunctionSpec);
}

extension type MTL4BinaryFunctionDescriptor._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject, objc.NSCopying {
  /// Constructs a [MTL4BinaryFunctionDescriptor] that points to the same underlying object as [other].
  MTL4BinaryFunctionDescriptor.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunctionDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [MTL4BinaryFunctionDescriptor] that wraps the given raw object pointer.
  MTL4BinaryFunctionDescriptor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunctionDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [MTL4BinaryFunctionDescriptor].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_MTL4BinaryFunctionDescriptor,
        );

  static MTL4BinaryFunctionDescriptor alloc() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4BinaryFunctionDescriptor,
      _sel_alloc,
    );
    return MTL4BinaryFunctionDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4BinaryFunctionDescriptor allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_hnh8cc(
      _class_MTL4BinaryFunctionDescriptor,
      _sel_allocWithZone_,
      zone,
    );
    return MTL4BinaryFunctionDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4BinaryFunctionDescriptor new$() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4BinaryFunctionDescriptor,
      _sel_new,
    );
    return MTL4BinaryFunctionDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of MTL4BinaryFunctionDescriptor constructed with the default `new` method.
  MTL4BinaryFunctionDescriptor() : this.as(new$());
}

extension MTL4BinaryFunctionDescriptor$Methods on MTL4BinaryFunctionDescriptor {
  MTL4FunctionDescriptor get functionDescriptor {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunctionDescriptor.functionDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_functionDescriptor,
    );
    return MTL4FunctionDescriptor.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }

  MTL4BinaryFunctionDescriptor init() {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunctionDescriptor.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return MTL4BinaryFunctionDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  objc.NSString get name {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunctionDescriptor.name',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(object$.ref.pointer, _sel_name);
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  int get options {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunctionDescriptor.options',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    return _objc_msgSend_ja34pm(object$.ref.pointer, _sel_options);
  }

  set functionDescriptor(MTL4FunctionDescriptor value) {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunctionDescriptor.setFunctionDescriptor:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setFunctionDescriptor_,
      value.ref.pointer,
    );
  }

  set name(objc.NSString value) {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunctionDescriptor.setName:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setName_,
      value.ref.pointer,
    );
  }

  set options(int value) {
    objc.checkOsVersionInternal(
      'MTL4BinaryFunctionDescriptor.setOptions:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1hmzq5q(object$.ref.pointer, _sel_setOptions_, value);
  }
}

sealed class MTL4BinaryFunctionOptions {
  static const MTL4BinaryFunctionOptionNone = 0;
  static const MTL4BinaryFunctionOptionPipelineIndependent = 2;
}

extension type MTL4ComputePipelineDescriptor._(objc.ObjCObject object$)
    implements objc.ObjCObject, MTL4PipelineDescriptor {
  /// Constructs a [MTL4ComputePipelineDescriptor] that points to the same underlying object as [other].
  MTL4ComputePipelineDescriptor.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [MTL4ComputePipelineDescriptor] that wraps the given raw object pointer.
  MTL4ComputePipelineDescriptor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [MTL4ComputePipelineDescriptor].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_MTL4ComputePipelineDescriptor,
        );

  static MTL4ComputePipelineDescriptor alloc() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4ComputePipelineDescriptor,
      _sel_alloc,
    );
    return MTL4ComputePipelineDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4ComputePipelineDescriptor allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_hnh8cc(
      _class_MTL4ComputePipelineDescriptor,
      _sel_allocWithZone_,
      zone,
    );
    return MTL4ComputePipelineDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4ComputePipelineDescriptor new$() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4ComputePipelineDescriptor,
      _sel_new,
    );
    return MTL4ComputePipelineDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of MTL4ComputePipelineDescriptor constructed with the default `new` method.
  MTL4ComputePipelineDescriptor() : this.as(new$());
}

extension MTL4ComputePipelineDescriptor$Methods
    on MTL4ComputePipelineDescriptor {
  MTL4FunctionDescriptor? get computeFunctionDescriptor {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.computeFunctionDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_computeFunctionDescriptor,
    );
    return $ret.address == 0
        ? null
        : MTL4FunctionDescriptor.fromPointer($ret, retain: true, release: true);
  }

  MTL4ComputePipelineDescriptor init() {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return MTL4ComputePipelineDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  int get maxTotalThreadsPerThreadgroup {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.maxTotalThreadsPerThreadgroup',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    return _objc_msgSend_84sea1(
      object$.ref.pointer,
      _sel_maxTotalThreadsPerThreadgroup,
    );
  }

  MTLSize get requiredThreadsPerThreadgroup {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.requiredThreadsPerThreadgroup',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ptr = pkg_ffi.calloc<MTLSize>();
    objc.useMsgSendVariants
        ? _objc_msgSend_1pge9dxStret(
            $ptr,
            object$.ref.pointer,
            _sel_requiredThreadsPerThreadgroup,
          )
        : $ptr.ref = _objc_msgSend_1pge9dx(
            object$.ref.pointer,
            _sel_requiredThreadsPerThreadgroup,
          );
    final $finalizable = $ptr.cast<ffi.Uint8>().asTypedList(
      ffi.sizeOf<MTLSize>(),
      finalizer: pkg_ffi.calloc.nativeFree,
    );
    return ffi.Struct.create<MTLSize>($finalizable);
  }

  void reset() {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.reset',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1hfer5h(object$.ref.pointer, _sel_reset);
  }

  set computeFunctionDescriptor(MTL4FunctionDescriptor? value) {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.setComputeFunctionDescriptor:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setComputeFunctionDescriptor_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }

  set maxTotalThreadsPerThreadgroup(int value) {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.setMaxTotalThreadsPerThreadgroup:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_hmwpbn(
      object$.ref.pointer,
      _sel_setMaxTotalThreadsPerThreadgroup_,
      value,
    );
  }

  set requiredThreadsPerThreadgroup(MTLSize value) {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.setRequiredThreadsPerThreadgroup:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1jj7uje(
      object$.ref.pointer,
      _sel_setRequiredThreadsPerThreadgroup_,
      value,
    );
  }

  set staticLinkingDescriptor(MTL4StaticLinkingDescriptor? value) {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.setStaticLinkingDescriptor:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setStaticLinkingDescriptor_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }

  set supportBinaryLinking(bool value) {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.setSupportBinaryLinking:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_68r7jb(
      object$.ref.pointer,
      _sel_setSupportBinaryLinking_,
      value,
    );
  }

  set supportIndirectCommandBuffers(
    MTL4IndirectCommandBufferSupportState value,
  ) {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.setSupportIndirectCommandBuffers:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_oyrzz3(
      object$.ref.pointer,
      _sel_setSupportIndirectCommandBuffers_,
      value.value,
    );
  }

  set threadGroupSizeIsMultipleOfThreadExecutionWidth(bool value) {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.setThreadGroupSizeIsMultipleOfThreadExecutionWidth:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_68r7jb(
      object$.ref.pointer,
      _sel_setThreadGroupSizeIsMultipleOfThreadExecutionWidth_,
      value,
    );
  }

  MTL4StaticLinkingDescriptor? get staticLinkingDescriptor {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.staticLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_staticLinkingDescriptor,
    );
    return $ret.address == 0
        ? null
        : MTL4StaticLinkingDescriptor.fromPointer(
            $ret,
            retain: true,
            release: true,
          );
  }

  bool get supportBinaryLinking {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.supportBinaryLinking',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    return _objc_msgSend_7utsvh(object$.ref.pointer, _sel_supportBinaryLinking);
  }

  MTL4IndirectCommandBufferSupportState get supportIndirectCommandBuffers {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.supportIndirectCommandBuffers',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_hrzrnp(
      object$.ref.pointer,
      _sel_supportIndirectCommandBuffers,
    );
    return MTL4IndirectCommandBufferSupportState.fromValue($ret);
  }

  bool get threadGroupSizeIsMultipleOfThreadExecutionWidth {
    objc.checkOsVersionInternal(
      'MTL4ComputePipelineDescriptor.threadGroupSizeIsMultipleOfThreadExecutionWidth',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    return _objc_msgSend_7utsvh(
      object$.ref.pointer,
      _sel_threadGroupSizeIsMultipleOfThreadExecutionWidth,
    );
  }
}

extension type MTL4FunctionDescriptor._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject, objc.NSCopying {
  /// Constructs a [MTL4FunctionDescriptor] that points to the same underlying object as [other].
  MTL4FunctionDescriptor.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'MTL4FunctionDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [MTL4FunctionDescriptor] that wraps the given raw object pointer.
  MTL4FunctionDescriptor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'MTL4FunctionDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [MTL4FunctionDescriptor].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_MTL4FunctionDescriptor,
        );

  static MTL4FunctionDescriptor alloc() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4FunctionDescriptor,
      _sel_alloc,
    );
    return MTL4FunctionDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4FunctionDescriptor allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_hnh8cc(
      _class_MTL4FunctionDescriptor,
      _sel_allocWithZone_,
      zone,
    );
    return MTL4FunctionDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4FunctionDescriptor new$() {
    final $ret = _objc_msgSend_1dfwsa3(_class_MTL4FunctionDescriptor, _sel_new);
    return MTL4FunctionDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of MTL4FunctionDescriptor constructed with the default `new` method.
  MTL4FunctionDescriptor() : this.as(new$());
}

extension MTL4FunctionDescriptor$Methods on MTL4FunctionDescriptor {
  MTL4FunctionDescriptor init() {
    objc.checkOsVersionInternal(
      'MTL4FunctionDescriptor.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return MTL4FunctionDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }
}

enum MTL4IndirectCommandBufferSupportState {
  MTL4IndirectCommandBufferSupportStateDisabled(0),
  MTL4IndirectCommandBufferSupportStateEnabled(1);

  final int value;
  const MTL4IndirectCommandBufferSupportState(this.value);

  static MTL4IndirectCommandBufferSupportState fromValue(int value) =>
      switch (value) {
        0 => MTL4IndirectCommandBufferSupportStateDisabled,
        1 => MTL4IndirectCommandBufferSupportStateEnabled,
        _ => throw ArgumentError(
          'Unknown value for MTL4IndirectCommandBufferSupportState: $value',
        ),
      };
}

extension type MTL4PipelineDescriptor._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject, objc.NSCopying {
  /// Constructs a [MTL4PipelineDescriptor] that points to the same underlying object as [other].
  MTL4PipelineDescriptor.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'MTL4PipelineDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [MTL4PipelineDescriptor] that wraps the given raw object pointer.
  MTL4PipelineDescriptor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'MTL4PipelineDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [MTL4PipelineDescriptor].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_MTL4PipelineDescriptor,
        );

  static MTL4PipelineDescriptor alloc() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4PipelineDescriptor,
      _sel_alloc,
    );
    return MTL4PipelineDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4PipelineDescriptor allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_hnh8cc(
      _class_MTL4PipelineDescriptor,
      _sel_allocWithZone_,
      zone,
    );
    return MTL4PipelineDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4PipelineDescriptor new$() {
    final $ret = _objc_msgSend_1dfwsa3(_class_MTL4PipelineDescriptor, _sel_new);
    return MTL4PipelineDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of MTL4PipelineDescriptor constructed with the default `new` method.
  MTL4PipelineDescriptor() : this.as(new$());
}

extension MTL4PipelineDescriptor$Methods on MTL4PipelineDescriptor {
  MTL4PipelineDescriptor init() {
    objc.checkOsVersionInternal(
      'MTL4PipelineDescriptor.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return MTL4PipelineDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  objc.NSString? get label {
    objc.checkOsVersionInternal(
      'MTL4PipelineDescriptor.label',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(object$.ref.pointer, _sel_label);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  MTL4PipelineOptions? get options {
    objc.checkOsVersionInternal(
      'MTL4PipelineDescriptor.options',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(object$.ref.pointer, _sel_options);
    return $ret.address == 0
        ? null
        : MTL4PipelineOptions.fromPointer($ret, retain: true, release: true);
  }

  set label(objc.NSString? value) {
    objc.checkOsVersionInternal(
      'MTL4PipelineDescriptor.setLabel:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setLabel_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }

  set options(MTL4PipelineOptions? value) {
    objc.checkOsVersionInternal(
      'MTL4PipelineDescriptor.setOptions:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setOptions_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }
}

/// WARNING: MTL4PipelineOptions is a stub. To generate bindings for this class, include
/// MTL4PipelineOptions in your config's objc-interfaces list.
///
extension type MTL4PipelineOptions._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject, objc.NSCopying {
  /// Constructs a [MTL4PipelineOptions] that points to the same underlying object as [other].
  MTL4PipelineOptions.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'MTL4PipelineOptions',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
  }

  /// Constructs a [MTL4PipelineOptions] that wraps the given raw object pointer.
  MTL4PipelineOptions.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'MTL4PipelineOptions',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
  }
}

extension type MTL4PipelineStageDynamicLinkingDescriptor._(
  objc.ObjCObject object$
)
    implements objc.ObjCObject, objc.NSObject, objc.NSCopying {
  /// Constructs a [MTL4PipelineStageDynamicLinkingDescriptor] that points to the same underlying object as [other].
  MTL4PipelineStageDynamicLinkingDescriptor.as(objc.ObjCObject other)
    : object$ = other {
    objc.checkOsVersionInternal(
      'MTL4PipelineStageDynamicLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [MTL4PipelineStageDynamicLinkingDescriptor] that wraps the given raw object pointer.
  MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'MTL4PipelineStageDynamicLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [MTL4PipelineStageDynamicLinkingDescriptor].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_MTL4PipelineStageDynamicLinkingDescriptor,
        );

  static MTL4PipelineStageDynamicLinkingDescriptor alloc() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4PipelineStageDynamicLinkingDescriptor,
      _sel_alloc,
    );
    return MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4PipelineStageDynamicLinkingDescriptor allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_hnh8cc(
      _class_MTL4PipelineStageDynamicLinkingDescriptor,
      _sel_allocWithZone_,
      zone,
    );
    return MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4PipelineStageDynamicLinkingDescriptor new$() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4PipelineStageDynamicLinkingDescriptor,
      _sel_new,
    );
    return MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of MTL4PipelineStageDynamicLinkingDescriptor constructed with the default `new` method.
  MTL4PipelineStageDynamicLinkingDescriptor() : this.as(new$());
}

extension MTL4PipelineStageDynamicLinkingDescriptor$Methods
    on MTL4PipelineStageDynamicLinkingDescriptor {
  objc.NSArray? get binaryLinkedFunctions {
    objc.checkOsVersionInternal(
      'MTL4PipelineStageDynamicLinkingDescriptor.binaryLinkedFunctions',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_binaryLinkedFunctions,
    );
    return $ret.address == 0
        ? null
        : objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  MTL4PipelineStageDynamicLinkingDescriptor init() {
    objc.checkOsVersionInternal(
      'MTL4PipelineStageDynamicLinkingDescriptor.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  int get maxCallStackDepth {
    objc.checkOsVersionInternal(
      'MTL4PipelineStageDynamicLinkingDescriptor.maxCallStackDepth',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    return _objc_msgSend_84sea1(object$.ref.pointer, _sel_maxCallStackDepth);
  }

  objc.NSArray get preloadedLibraries {
    objc.checkOsVersionInternal(
      'MTL4PipelineStageDynamicLinkingDescriptor.preloadedLibraries',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_preloadedLibraries,
    );
    return objc.NSArray.fromPointer($ret, retain: true, release: true);
  }

  set binaryLinkedFunctions(objc.NSArray? value) {
    objc.checkOsVersionInternal(
      'MTL4PipelineStageDynamicLinkingDescriptor.setBinaryLinkedFunctions:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setBinaryLinkedFunctions_,
      value?.ref.pointer ?? ffi.nullptr,
    );
  }

  set maxCallStackDepth(int value) {
    objc.checkOsVersionInternal(
      'MTL4PipelineStageDynamicLinkingDescriptor.setMaxCallStackDepth:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_hmwpbn(
      object$.ref.pointer,
      _sel_setMaxCallStackDepth_,
      value,
    );
  }

  set preloadedLibraries(objc.NSArray value) {
    objc.checkOsVersionInternal(
      'MTL4PipelineStageDynamicLinkingDescriptor.setPreloadedLibraries:',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    _objc_msgSend_1h6563x(
      object$.ref.pointer,
      _sel_setPreloadedLibraries_,
      value.ref.pointer,
    );
  }
}

extension type MTL4RenderPipelineDynamicLinkingDescriptor._(
  objc.ObjCObject object$
)
    implements objc.ObjCObject, objc.NSObject, objc.NSCopying {
  /// Constructs a [MTL4RenderPipelineDynamicLinkingDescriptor] that points to the same underlying object as [other].
  MTL4RenderPipelineDynamicLinkingDescriptor.as(objc.ObjCObject other)
    : object$ = other {
    objc.checkOsVersionInternal(
      'MTL4RenderPipelineDynamicLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Constructs a [MTL4RenderPipelineDynamicLinkingDescriptor] that wraps the given raw object pointer.
  MTL4RenderPipelineDynamicLinkingDescriptor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'MTL4RenderPipelineDynamicLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [MTL4RenderPipelineDynamicLinkingDescriptor].
  static bool isA(objc.ObjCObject? obj) => obj == null
      ? false
      : _objc_msgSend_xat5dx(
          obj.ref.pointer,
          _sel_isKindOfClass_,
          _class_MTL4RenderPipelineDynamicLinkingDescriptor,
        );

  static MTL4RenderPipelineDynamicLinkingDescriptor alloc() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4RenderPipelineDynamicLinkingDescriptor,
      _sel_alloc,
    );
    return MTL4RenderPipelineDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4RenderPipelineDynamicLinkingDescriptor allocWithZone(
    ffi.Pointer<objc.NSZone> zone,
  ) {
    final $ret = _objc_msgSend_hnh8cc(
      _class_MTL4RenderPipelineDynamicLinkingDescriptor,
      _sel_allocWithZone_,
      zone,
    );
    return MTL4RenderPipelineDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  static MTL4RenderPipelineDynamicLinkingDescriptor new$() {
    final $ret = _objc_msgSend_1dfwsa3(
      _class_MTL4RenderPipelineDynamicLinkingDescriptor,
      _sel_new,
    );
    return MTL4RenderPipelineDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  /// Returns a new instance of MTL4RenderPipelineDynamicLinkingDescriptor constructed with the default `new` method.
  MTL4RenderPipelineDynamicLinkingDescriptor() : this.as(new$());
}

extension MTL4RenderPipelineDynamicLinkingDescriptor$Methods
    on MTL4RenderPipelineDynamicLinkingDescriptor {
  MTL4PipelineStageDynamicLinkingDescriptor get fragmentLinkingDescriptor {
    objc.checkOsVersionInternal(
      'MTL4RenderPipelineDynamicLinkingDescriptor.fragmentLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_fragmentLinkingDescriptor,
    );
    return MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }

  MTL4RenderPipelineDynamicLinkingDescriptor init() {
    objc.checkOsVersionInternal(
      'MTL4RenderPipelineDynamicLinkingDescriptor.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return MTL4RenderPipelineDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: false,
      release: true,
    );
  }

  MTL4PipelineStageDynamicLinkingDescriptor get meshLinkingDescriptor {
    objc.checkOsVersionInternal(
      'MTL4RenderPipelineDynamicLinkingDescriptor.meshLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_meshLinkingDescriptor,
    );
    return MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }

  MTL4PipelineStageDynamicLinkingDescriptor get objectLinkingDescriptor {
    objc.checkOsVersionInternal(
      'MTL4RenderPipelineDynamicLinkingDescriptor.objectLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_objectLinkingDescriptor,
    );
    return MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }

  MTL4PipelineStageDynamicLinkingDescriptor get tileLinkingDescriptor {
    objc.checkOsVersionInternal(
      'MTL4RenderPipelineDynamicLinkingDescriptor.tileLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_tileLinkingDescriptor,
    );
    return MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }

  MTL4PipelineStageDynamicLinkingDescriptor get vertexLinkingDescriptor {
    objc.checkOsVersionInternal(
      'MTL4RenderPipelineDynamicLinkingDescriptor.vertexLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
    final $ret = _objc_msgSend_1dfwsa3(
      object$.ref.pointer,
      _sel_vertexLinkingDescriptor,
    );
    return MTL4PipelineStageDynamicLinkingDescriptor.fromPointer(
      $ret,
      retain: true,
      release: true,
    );
  }
}

/// WARNING: MTL4StaticLinkingDescriptor is a stub. To generate bindings for this class, include
/// MTL4StaticLinkingDescriptor in your config's objc-interfaces list.
///
extension type MTL4StaticLinkingDescriptor._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject, objc.NSCopying {
  /// Constructs a [MTL4StaticLinkingDescriptor] that points to the same underlying object as [other].
  MTL4StaticLinkingDescriptor.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal(
      'MTL4StaticLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
  }

  /// Constructs a [MTL4StaticLinkingDescriptor] that wraps the given raw object pointer.
  MTL4StaticLinkingDescriptor.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal(
      'MTL4StaticLinkingDescriptor',
      iOS: (false, (26, 0, 0)),
      macOS: (false, (26, 0, 0)),
    );
  }
}

enum MTLFunctionType {
  MTLFunctionTypeVertex(1),
  MTLFunctionTypeFragment(2),
  MTLFunctionTypeKernel(3),
  MTLFunctionTypeVisible(5),
  MTLFunctionTypeIntersection(6),
  MTLFunctionTypeMesh(7),
  MTLFunctionTypeObject(8);

  final int value;
  const MTLFunctionType(this.value);

  static MTLFunctionType fromValue(int value) => switch (value) {
    1 => MTLFunctionTypeVertex,
    2 => MTLFunctionTypeFragment,
    3 => MTLFunctionTypeKernel,
    5 => MTLFunctionTypeVisible,
    6 => MTLFunctionTypeIntersection,
    7 => MTLFunctionTypeMesh,
    8 => MTLFunctionTypeObject,
    _ => throw ArgumentError('Unknown value for MTLFunctionType: $value'),
  };
}

final class MTLSize extends ffi.Struct {
  @ffi.UnsignedLong()
  external int width;

  @ffi.UnsignedLong()
  external int height;

  @ffi.UnsignedLong()
  external int depth;

  static ffi.Pointer<MTLSize> $allocate(
    ffi.Allocator $allocator, {
    required int width,
    required int height,
    required int depth,
  }) => $allocator<MTLSize>()
    ..ref.width = width
    ..ref.height = height
    ..ref.depth = depth;
}

/// Construction methods for `objc.ObjCBlock<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void>)>`.
abstract final class ObjCBlock_MTLFunctionType_ffiVoid {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void>)>
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void>)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void>)>
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void> arg0)>
    >
    ptr,
  ) => objc.ObjCBlock<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void>)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void>)>
  fromFunction(
    MTLFunctionType Function(ffi.Pointer<ffi.Void>) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void>)>(
    objc.newClosureBlock(
      _closureCallable,
      (ffi.Pointer<ffi.Void> arg0) => fn(arg0).value,
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  /// Native method trampoline for this block signature.
  static ffi.Pointer<ffi.Void> get protocolTrampoline =>
      ffi.Native.addressOf<
            ffi.NativeFunction<
              ffi.UnsignedLong Function(
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >(_114eave_protocolTrampoline_srgf34)
          .cast();

  static int _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.UnsignedLong Function(ffi.Pointer<ffi.Void> arg0)
        >
      >()
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.UnsignedLong Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >(_fnPtrTrampoline, 0)
          .cast();
  static int _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
  ) => (objc.getBlockClosure(block) as int Function(ffi.Pointer<ffi.Void>))(
    arg0,
  );
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.UnsignedLong Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >(_closureTrampoline, 0)
          .cast();
}

/// Call operator for `objc.ObjCBlock<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void>)>`.
extension ObjCBlock_MTLFunctionType_ffiVoid$CallExtension
    on objc.ObjCBlock<ffi.UnsignedLong Function(ffi.Pointer<ffi.Void>)> {
  MTLFunctionType call(ffi.Pointer<ffi.Void> arg0) => MTLFunctionType.fromValue(
    ref.pointer.ref.invoke
        .cast<
          ffi.NativeFunction<
            ffi.UnsignedLong Function(
              ffi.Pointer<objc.ObjCBlockImpl> block,
              ffi.Pointer<ffi.Void> arg0,
            )
          >
        >()
        .asFunction<
          int Function(ffi.Pointer<objc.ObjCBlockImpl>, ffi.Pointer<ffi.Void>)
        >()(ref.pointer, arg0),
  );
}

/// Construction methods for `objc.ObjCBlock<objc.NSString? Function(ffi.Pointer<ffi.Void>)>`.
abstract final class ObjCBlock_NSString_ffiVoid {
  /// Returns a block that wraps the given raw block pointer.
  static objc.ObjCBlock<objc.NSString? Function(ffi.Pointer<ffi.Void>)>
  fromPointer(
    ffi.Pointer<objc.ObjCBlockImpl> pointer, {
    bool retain = false,
    bool release = false,
  }) => objc.ObjCBlock<objc.NSString? Function(ffi.Pointer<ffi.Void>)>(
    pointer,
    retain: retain,
    release: release,
  );

  /// Creates a block from a C function pointer.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  static objc.ObjCBlock<objc.NSString? Function(ffi.Pointer<ffi.Void>)>
  fromFunctionPointer(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<ffi.Void> arg0)
      >
    >
    ptr,
  ) => objc.ObjCBlock<objc.NSString? Function(ffi.Pointer<ffi.Void>)>(
    objc.newPointerBlock(_fnPtrCallable, ptr.cast()),
    retain: false,
    release: true,
  );

  /// Creates a block from a Dart function.
  ///
  /// This block must be invoked by native code running on the same thread as
  /// the isolate that registered it. Invoking the block on the wrong thread
  /// will result in a crash.
  ///
  /// If `keepIsolateAlive` is true, this block will keep this isolate alive
  /// until it is garbage collected by both Dart and ObjC.
  static objc.ObjCBlock<objc.NSString? Function(ffi.Pointer<ffi.Void>)>
  fromFunction(
    objc.NSString? Function(ffi.Pointer<ffi.Void>) fn, {
    bool keepIsolateAlive = true,
  }) => objc.ObjCBlock<objc.NSString? Function(ffi.Pointer<ffi.Void>)>(
    objc.newClosureBlock(
      _closureCallable,
      (ffi.Pointer<ffi.Void> arg0) =>
          fn(arg0)?.ref.retainAndAutorelease() ?? ffi.nullptr,
      keepIsolateAlive,
    ),
    retain: false,
    release: true,
  );

  /// Native method trampoline for this block signature.
  static ffi.Pointer<ffi.Void> get protocolTrampoline =>
      ffi.Native.addressOf<
            ffi.NativeFunction<
              ffi.Pointer<objc.ObjCObjectImpl> Function(
                ffi.Pointer<objc.ObjCObjectImpl>,
                ffi.Pointer<ffi.Void>,
              )
            >
          >(_114eave_protocolTrampoline_1mbt9g9)
          .cast();

  static ffi.Pointer<objc.ObjCObjectImpl> _fnPtrTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
  ) => block.ref.target
      .cast<
        ffi.NativeFunction<
          ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<ffi.Void> arg0)
        >
      >()
      .asFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<ffi.Void>)
      >()(arg0);
  static ffi.Pointer<ffi.Void> _fnPtrCallable =
      ffi.Pointer.fromFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >(_fnPtrTrampoline)
          .cast();
  static ffi.Pointer<objc.ObjCObjectImpl> _closureTrampoline(
    ffi.Pointer<objc.ObjCBlockImpl> block,
    ffi.Pointer<ffi.Void> arg0,
  ) =>
      (objc.getBlockClosure(block)
          as ffi.Pointer<objc.ObjCObjectImpl> Function(ffi.Pointer<ffi.Void>))(
        arg0,
      );
  static ffi.Pointer<ffi.Void> _closureCallable =
      ffi.Pointer.fromFunction<
            ffi.Pointer<objc.ObjCObjectImpl> Function(
              ffi.Pointer<objc.ObjCBlockImpl>,
              ffi.Pointer<ffi.Void>,
            )
          >(_closureTrampoline)
          .cast();
}

/// Call operator for `objc.ObjCBlock<objc.NSString? Function(ffi.Pointer<ffi.Void>)>`.
extension ObjCBlock_NSString_ffiVoid$CallExtension
    on objc.ObjCBlock<objc.NSString? Function(ffi.Pointer<ffi.Void>)> {
  objc.NSString? call(ffi.Pointer<ffi.Void> arg0) =>
      ref.pointer.ref.invoke
              .cast<
                ffi.NativeFunction<
                  ffi.Pointer<objc.ObjCObjectImpl> Function(
                    ffi.Pointer<objc.ObjCBlockImpl> block,
                    ffi.Pointer<ffi.Void> arg0,
                  )
                >
              >()
              .asFunction<
                ffi.Pointer<objc.ObjCObjectImpl> Function(
                  ffi.Pointer<objc.ObjCBlockImpl>,
                  ffi.Pointer<ffi.Void>,
                )
              >()(ref.pointer, arg0)
              .address ==
          0
      ? null
      : objc.NSString.fromPointer(
          ref.pointer.ref.invoke
              .cast<
                ffi.NativeFunction<
                  ffi.Pointer<objc.ObjCObjectImpl> Function(
                    ffi.Pointer<objc.ObjCBlockImpl> block,
                    ffi.Pointer<ffi.Void> arg0,
                  )
                >
              >()
              .asFunction<
                ffi.Pointer<objc.ObjCObjectImpl> Function(
                  ffi.Pointer<objc.ObjCBlockImpl>,
                  ffi.Pointer<ffi.Void>,
                )
              >()(ref.pointer, arg0),
          retain: true,
          release: true,
        );
}

late final _class_MTL4BinaryFunctionDescriptor = objc.getClass(
  "MTL4BinaryFunctionDescriptor",
);
late final _class_MTL4ComputePipelineDescriptor = objc.getClass(
  "MTL4ComputePipelineDescriptor",
);
late final _class_MTL4FunctionDescriptor = objc.getClass(
  "MTL4FunctionDescriptor",
);
late final _class_MTL4PipelineDescriptor = objc.getClass(
  "MTL4PipelineDescriptor",
);
late final _class_MTL4PipelineStageDynamicLinkingDescriptor = objc.getClass(
  "MTL4PipelineStageDynamicLinkingDescriptor",
);
late final _class_MTL4RenderPipelineDynamicLinkingDescriptor = objc.getClass(
  "MTL4RenderPipelineDynamicLinkingDescriptor",
);
final _objc_msgSend_1dfwsa3 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1h6563x = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1hfer5h = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1hmzq5q = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.UnsignedLong,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_1jj7uje = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          MTLSize,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        MTLSize,
      )
    >();
final _objc_msgSend_1pge9dx = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        MTLSize Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      MTLSize Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1pge9dxStret = objc.msgSendStretPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<MTLSize>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<MTLSize>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_68r7jb = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Bool,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        bool,
      )
    >();
final _objc_msgSend_7utsvh = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_84sea1 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.UnsignedLong Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_hmwpbn = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.UnsignedLong,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_hnh8cc = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
final _objc_msgSend_hrzrnp = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Long Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_ja34pm = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.UnsignedLong Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_oyrzz3 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      void Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
final _objc_msgSend_rvdyxc = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCProtocolImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCProtocolImpl>,
      )
    >();
final _objc_msgSend_xat5dx = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_yjrosu = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.UnsignedLong Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _protocol_MTL4BinaryFunction = objc.getProtocol(
  "MTL4BinaryFunction",
);
late final _sel_alloc = objc.registerName("alloc");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
late final _sel_binaryLinkedFunctions = objc.registerName(
  "binaryLinkedFunctions",
);
late final _sel_computeFunctionDescriptor = objc.registerName(
  "computeFunctionDescriptor",
);
late final _sel_conformsToProtocol_ = objc.registerName("conformsToProtocol:");
late final _sel_fragmentLinkingDescriptor = objc.registerName(
  "fragmentLinkingDescriptor",
);
late final _sel_functionDescriptor = objc.registerName("functionDescriptor");
late final _sel_functionType = objc.registerName("functionType");
late final _sel_init = objc.registerName("init");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
late final _sel_label = objc.registerName("label");
late final _sel_maxCallStackDepth = objc.registerName("maxCallStackDepth");
late final _sel_maxTotalThreadsPerThreadgroup = objc.registerName(
  "maxTotalThreadsPerThreadgroup",
);
late final _sel_meshLinkingDescriptor = objc.registerName(
  "meshLinkingDescriptor",
);
late final _sel_name = objc.registerName("name");
late final _sel_new = objc.registerName("new");
late final _sel_objectLinkingDescriptor = objc.registerName(
  "objectLinkingDescriptor",
);
late final _sel_options = objc.registerName("options");
late final _sel_preloadedLibraries = objc.registerName("preloadedLibraries");
late final _sel_requiredThreadsPerThreadgroup = objc.registerName(
  "requiredThreadsPerThreadgroup",
);
late final _sel_reset = objc.registerName("reset");
late final _sel_setBinaryLinkedFunctions_ = objc.registerName(
  "setBinaryLinkedFunctions:",
);
late final _sel_setComputeFunctionDescriptor_ = objc.registerName(
  "setComputeFunctionDescriptor:",
);
late final _sel_setFunctionDescriptor_ = objc.registerName(
  "setFunctionDescriptor:",
);
late final _sel_setLabel_ = objc.registerName("setLabel:");
late final _sel_setMaxCallStackDepth_ = objc.registerName(
  "setMaxCallStackDepth:",
);
late final _sel_setMaxTotalThreadsPerThreadgroup_ = objc.registerName(
  "setMaxTotalThreadsPerThreadgroup:",
);
late final _sel_setName_ = objc.registerName("setName:");
late final _sel_setOptions_ = objc.registerName("setOptions:");
late final _sel_setPreloadedLibraries_ = objc.registerName(
  "setPreloadedLibraries:",
);
late final _sel_setRequiredThreadsPerThreadgroup_ = objc.registerName(
  "setRequiredThreadsPerThreadgroup:",
);
late final _sel_setStaticLinkingDescriptor_ = objc.registerName(
  "setStaticLinkingDescriptor:",
);
late final _sel_setSupportBinaryLinking_ = objc.registerName(
  "setSupportBinaryLinking:",
);
late final _sel_setSupportIndirectCommandBuffers_ = objc.registerName(
  "setSupportIndirectCommandBuffers:",
);
late final _sel_setThreadGroupSizeIsMultipleOfThreadExecutionWidth_ = objc
    .registerName("setThreadGroupSizeIsMultipleOfThreadExecutionWidth:");
late final _sel_staticLinkingDescriptor = objc.registerName(
  "staticLinkingDescriptor",
);
late final _sel_supportBinaryLinking = objc.registerName(
  "supportBinaryLinking",
);
late final _sel_supportIndirectCommandBuffers = objc.registerName(
  "supportIndirectCommandBuffers",
);
late final _sel_threadGroupSizeIsMultipleOfThreadExecutionWidth = objc
    .registerName("threadGroupSizeIsMultipleOfThreadExecutionWidth");
late final _sel_tileLinkingDescriptor = objc.registerName(
  "tileLinkingDescriptor",
);
late final _sel_vertexLinkingDescriptor = objc.registerName(
  "vertexLinkingDescriptor",
);
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
